/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin.feedback'
import { Route as AuthenticatedAdminLoginProvidersRouteImport } from './routes/_authenticated/admin.login-providers'
import { Route as AuthenticatedAdminModelsRouteImport } from './routes/_authenticated/admin.models'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSurveysRouteImport } from './routes/_authenticated/admin.surveys'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWorkspacesRouteImport } from './routes/_authenticated/admin.workspaces'
import { Route as AuthenticatedWWorkspaceSlugRouteRouteImport } from './routes/_authenticated/w/$workspaceSlug/route'
import { Route as WWorkspaceSlugLoginRouteImport } from './routes/w/$workspaceSlug/login'
import { Route as AuthenticatedAdminCatalogIndexRouteImport } from './routes/_authenticated/admin.catalog.index'
import { Route as AuthenticatedWWorkspaceSlugIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/index'
import { Route as AuthenticatedWWorkspaceSlugActivityRouteImport } from './routes/_authenticated/w/$workspaceSlug/activity'
import { Route as AuthenticatedWWorkspaceSlugAdminRouteRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/route'
import { Route as AuthenticatedWWorkspaceSlugMentorRouteImport } from './routes/_authenticated/w/$workspaceSlug/mentor'
import { Route as AuthenticatedWWorkspaceSlugOnboardingRouteImport } from './routes/_authenticated/w/$workspaceSlug/onboarding'
import { Route as AuthenticatedWWorkspaceSlugPracticeProfileRouteImport } from './routes/_authenticated/w/$workspaceSlug/practice-profile'
import { Route as AuthenticatedWWorkspaceSlugReviewsRouteImport } from './routes/_authenticated/w/$workspaceSlug/reviews'
import { Route as AuthenticatedWWorkspaceSlugWorkspaceActivityRouteImport } from './routes/_authenticated/w/$workspaceSlug/workspace-activity'
import { Route as AuthenticatedWorkspacesNewIndexRouteImport } from './routes/_authenticated/workspaces/new/index'
import { Route as AuthenticatedWorkspacesNewGithubRouteImport } from './routes/_authenticated/workspaces/new/github'
import { Route as AuthenticatedWorkspacesNewGitlabRouteImport } from './routes/_authenticated/workspaces/new/gitlab'
import { Route as AuthenticatedAdminWorkspacesWorkspaceSlugUsersRouteImport } from './routes/_authenticated/admin.workspaces_.$workspaceSlug.users'
import { Route as AuthenticatedWWorkspaceSlugAdminAuditRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/audit'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations'
import { Route as AuthenticatedWWorkspaceSlugAdminMembersRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/members'
import { Route as AuthenticatedWWorkspaceSlugAdminModelsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/models'
import { Route as AuthenticatedWWorkspaceSlugAdminOnboardingRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/onboarding'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices'
import { Route as AuthenticatedWWorkspaceSlugAdminSettingsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/settings'
import { Route as AuthenticatedWWorkspaceSlugAdminTeamsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/teams'
import { Route as AuthenticatedWWorkspaceSlugAdminUsageRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/usage'
import { Route as AuthenticatedWWorkspaceSlugMentorIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/mentor/index'
import { Route as AuthenticatedWWorkspaceSlugMentorThreadIdRouteImport } from './routes/_authenticated/w/$workspaceSlug/mentor/$threadId'
import { Route as AuthenticatedWWorkspaceSlugReviewsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/reviews/index'
import { Route as AuthenticatedWWorkspaceSlugTeamsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/teams/index'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/index'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/outline'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsScmRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/scm'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/slack'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/index'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReleasesRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/releases'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReviewRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/review'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/reviews'
import { Route as AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRouteImport } from './routes/_authenticated/w/$workspaceSlug/reviews/$artifactKind.$artifactId'
import { Route as AuthenticatedWWorkspaceSlugUserUsernameIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/user/$username/index'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/reviews/index'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/reviews/feedback'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/reviews/observations'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/reviews/runs'
import { Route as AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRouteImport } from './routes/_authenticated/w/$workspaceSlug/user/$username/practice-groups.$groupSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLoginProvidersRoute =
  AuthenticatedAdminLoginProvidersRouteImport.update({
    id: '/login-providers',
    path: '/login-providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModelsRoute =
  AuthenticatedAdminModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSurveysRoute =
  AuthenticatedAdminSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWorkspacesRoute =
  AuthenticatedAdminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedWWorkspaceSlugRouteRoute =
  AuthenticatedWWorkspaceSlugRouteRouteImport.update({
    id: '/w/$workspaceSlug',
    path: '/w/$workspaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WWorkspaceSlugLoginRoute = WWorkspaceSlugLoginRouteImport.update({
  id: '/w/$workspaceSlug/login',
  path: '/w/$workspaceSlug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCatalogIndexRoute =
  AuthenticatedAdminCatalogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCatalogRoute,
  } as any)
const AuthenticatedWWorkspaceSlugIndexRoute =
  AuthenticatedWWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugActivityRoute =
  AuthenticatedWWorkspaceSlugActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminRouteRoute =
  AuthenticatedWWorkspaceSlugAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugMentorRoute =
  AuthenticatedWWorkspaceSlugMentorRouteImport.update({
    id: '/mentor',
    path: '/mentor',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugOnboardingRoute =
  AuthenticatedWWorkspaceSlugOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugPracticeProfileRoute =
  AuthenticatedWWorkspaceSlugPracticeProfileRouteImport.update({
    id: '/practice-profile',
    path: '/practice-profile',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugReviewsRoute =
  AuthenticatedWWorkspaceSlugReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugWorkspaceActivityRoute =
  AuthenticatedWWorkspaceSlugWorkspaceActivityRouteImport.update({
    id: '/workspace-activity',
    path: '/workspace-activity',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesNewIndexRoute =
  AuthenticatedWorkspacesNewIndexRouteImport.update({
    id: '/workspaces/new/',
    path: '/workspaces/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesNewGithubRoute =
  AuthenticatedWorkspacesNewGithubRouteImport.update({
    id: '/workspaces/new/github',
    path: '/workspaces/new/github',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesNewGitlabRoute =
  AuthenticatedWorkspacesNewGitlabRouteImport.update({
    id: '/workspaces/new/gitlab',
    path: '/workspaces/new/gitlab',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute =
  AuthenticatedAdminWorkspacesWorkspaceSlugUsersRouteImport.update({
    id: '/workspaces_/$workspaceSlug/users',
    path: '/workspaces/$workspaceSlug/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminAuditRoute =
  AuthenticatedWWorkspaceSlugAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminMembersRoute =
  AuthenticatedWWorkspaceSlugAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminModelsRoute =
  AuthenticatedWWorkspaceSlugAdminModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminOnboardingRoute =
  AuthenticatedWWorkspaceSlugAdminOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesRouteImport.update({
    id: '/practices',
    path: '/practices',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminSettingsRoute =
  AuthenticatedWWorkspaceSlugAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminTeamsRoute =
  AuthenticatedWWorkspaceSlugAdminTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminUsageRoute =
  AuthenticatedWWorkspaceSlugAdminUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugMentorIndexRoute =
  AuthenticatedWWorkspaceSlugMentorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugMentorRoute,
  } as any)
const AuthenticatedWWorkspaceSlugMentorThreadIdRoute =
  AuthenticatedWWorkspaceSlugMentorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedWWorkspaceSlugMentorRoute,
  } as any)
const AuthenticatedWWorkspaceSlugReviewsIndexRoute =
  AuthenticatedWWorkspaceSlugReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugReviewsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugTeamsIndexRoute =
  AuthenticatedWWorkspaceSlugTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRouteImport.update({
    id: '/outline',
    path: '/outline',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsScmRouteImport.update({
    id: '/scm',
    path: '/scm',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRouteImport.update({
    id: '/slack',
    path: '/slack',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute =
  AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRouteImport.update({
    id: '/$artifactKind/$artifactId',
    path: '/$artifactKind/$artifactId',
    getParentRoute: () => AuthenticatedWWorkspaceSlugReviewsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugUserUsernameIndexRoute =
  AuthenticatedWWorkspaceSlugUserUsernameIndexRouteImport.update({
    id: '/user/$username/',
    path: '/user/$username/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRouteImport.update(
    {
      id: '/observations',
      path: '/observations',
      getParentRoute: () =>
        AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute,
    } as any,
  )
const AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute =
  AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRouteImport.update(
    {
      id: '/user/$username/practice-groups/$groupSlug',
      path: '/user/$username/practice-groups/$groupSlug',
      getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consent': typeof ConsentRoute
  '/imprint': typeof ImprintRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRouteWithChildren
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/login-providers': typeof AuthenticatedAdminLoginProvidersRoute
  '/admin/models': typeof AuthenticatedAdminModelsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/w/$workspaceSlug/login': typeof WWorkspaceSlugLoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/w/$workspaceSlug/admin': typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  '/w/$workspaceSlug/activity': typeof AuthenticatedWWorkspaceSlugActivityRoute
  '/w/$workspaceSlug/mentor': typeof AuthenticatedWWorkspaceSlugMentorRouteWithChildren
  '/w/$workspaceSlug/onboarding': typeof AuthenticatedWWorkspaceSlugOnboardingRoute
  '/w/$workspaceSlug/practice-profile': typeof AuthenticatedWWorkspaceSlugPracticeProfileRoute
  '/w/$workspaceSlug/reviews': typeof AuthenticatedWWorkspaceSlugReviewsRouteWithChildren
  '/w/$workspaceSlug/workspace-activity': typeof AuthenticatedWWorkspaceSlugWorkspaceActivityRoute
  '/workspaces/new/github': typeof AuthenticatedWorkspacesNewGithubRoute
  '/workspaces/new/gitlab': typeof AuthenticatedWorkspacesNewGitlabRoute
  '/admin/catalog/': typeof AuthenticatedAdminCatalogIndexRoute
  '/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/workspaces/new/': typeof AuthenticatedWorkspacesNewIndexRoute
  '/admin/workspaces/$workspaceSlug/users': typeof AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute
  '/w/$workspaceSlug/admin/audit': typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  '/w/$workspaceSlug/admin/integrations': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren
  '/w/$workspaceSlug/admin/members': typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  '/w/$workspaceSlug/admin/models': typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  '/w/$workspaceSlug/admin/onboarding': typeof AuthenticatedWWorkspaceSlugAdminOnboardingRoute
  '/w/$workspaceSlug/admin/practices': typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren
  '/w/$workspaceSlug/admin/settings': typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  '/w/$workspaceSlug/admin/teams': typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  '/w/$workspaceSlug/admin/usage': typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  '/w/$workspaceSlug/mentor/$threadId': typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  '/w/$workspaceSlug/mentor/': typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
  '/w/$workspaceSlug/reviews/': typeof AuthenticatedWWorkspaceSlugReviewsIndexRoute
  '/w/$workspaceSlug/teams/': typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  '/w/$workspaceSlug/admin/integrations/outline': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  '/w/$workspaceSlug/admin/integrations/scm': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  '/w/$workspaceSlug/admin/integrations/slack': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  '/w/$workspaceSlug/admin/practices/releases': typeof AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute
  '/w/$workspaceSlug/admin/practices/review': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute
  '/w/$workspaceSlug/admin/practices/reviews': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteWithChildren
  '/w/$workspaceSlug/reviews/$artifactKind/$artifactId': typeof AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute
  '/w/$workspaceSlug/admin/integrations/': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
  '/w/$workspaceSlug/admin/practices/': typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
  '/w/$workspaceSlug/user/$username/': typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
  '/w/$workspaceSlug/admin/practices/reviews/feedback': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute
  '/w/$workspaceSlug/admin/practices/reviews/observations': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute
  '/w/$workspaceSlug/admin/practices/reviews/runs': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute
  '/w/$workspaceSlug/user/$username/practice-groups/$groupSlug': typeof AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute
  '/w/$workspaceSlug/admin/practices/reviews/': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consent': typeof ConsentRoute
  '/imprint': typeof ImprintRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/login-providers': typeof AuthenticatedAdminLoginProvidersRoute
  '/admin/models': typeof AuthenticatedAdminModelsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/w/$workspaceSlug/login': typeof WWorkspaceSlugLoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/w/$workspaceSlug/admin': typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  '/w/$workspaceSlug/activity': typeof AuthenticatedWWorkspaceSlugActivityRoute
  '/w/$workspaceSlug/onboarding': typeof AuthenticatedWWorkspaceSlugOnboardingRoute
  '/w/$workspaceSlug/practice-profile': typeof AuthenticatedWWorkspaceSlugPracticeProfileRoute
  '/w/$workspaceSlug/workspace-activity': typeof AuthenticatedWWorkspaceSlugWorkspaceActivityRoute
  '/workspaces/new/github': typeof AuthenticatedWorkspacesNewGithubRoute
  '/workspaces/new/gitlab': typeof AuthenticatedWorkspacesNewGitlabRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogIndexRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/workspaces/new': typeof AuthenticatedWorkspacesNewIndexRoute
  '/admin/workspaces/$workspaceSlug/users': typeof AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute
  '/w/$workspaceSlug/admin/audit': typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  '/w/$workspaceSlug/admin/members': typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  '/w/$workspaceSlug/admin/models': typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  '/w/$workspaceSlug/admin/onboarding': typeof AuthenticatedWWorkspaceSlugAdminOnboardingRoute
  '/w/$workspaceSlug/admin/settings': typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  '/w/$workspaceSlug/admin/teams': typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  '/w/$workspaceSlug/admin/usage': typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  '/w/$workspaceSlug/mentor/$threadId': typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  '/w/$workspaceSlug/mentor': typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
  '/w/$workspaceSlug/reviews': typeof AuthenticatedWWorkspaceSlugReviewsIndexRoute
  '/w/$workspaceSlug/teams': typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  '/w/$workspaceSlug/admin/integrations/outline': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  '/w/$workspaceSlug/admin/integrations/scm': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  '/w/$workspaceSlug/admin/integrations/slack': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  '/w/$workspaceSlug/admin/practices/releases': typeof AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute
  '/w/$workspaceSlug/admin/practices/review': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute
  '/w/$workspaceSlug/reviews/$artifactKind/$artifactId': typeof AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute
  '/w/$workspaceSlug/admin/integrations': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
  '/w/$workspaceSlug/admin/practices': typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
  '/w/$workspaceSlug/user/$username': typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
  '/w/$workspaceSlug/admin/practices/reviews/feedback': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute
  '/w/$workspaceSlug/admin/practices/reviews/observations': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute
  '/w/$workspaceSlug/admin/practices/reviews/runs': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute
  '/w/$workspaceSlug/user/$username/practice-groups/$groupSlug': typeof AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute
  '/w/$workspaceSlug/admin/practices/reviews': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/consent': typeof ConsentRoute
  '/imprint': typeof ImprintRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/_authenticated/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRouteWithChildren
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/login-providers': typeof AuthenticatedAdminLoginProvidersRoute
  '/_authenticated/admin/models': typeof AuthenticatedAdminModelsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/w/$workspaceSlug/login': typeof WWorkspaceSlugLoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/w/$workspaceSlug/admin': typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  '/_authenticated/w/$workspaceSlug/activity': typeof AuthenticatedWWorkspaceSlugActivityRoute
  '/_authenticated/w/$workspaceSlug/mentor': typeof AuthenticatedWWorkspaceSlugMentorRouteWithChildren
  '/_authenticated/w/$workspaceSlug/onboarding': typeof AuthenticatedWWorkspaceSlugOnboardingRoute
  '/_authenticated/w/$workspaceSlug/practice-profile': typeof AuthenticatedWWorkspaceSlugPracticeProfileRoute
  '/_authenticated/w/$workspaceSlug/reviews': typeof AuthenticatedWWorkspaceSlugReviewsRouteWithChildren
  '/_authenticated/w/$workspaceSlug/workspace-activity': typeof AuthenticatedWWorkspaceSlugWorkspaceActivityRoute
  '/_authenticated/workspaces/new/github': typeof AuthenticatedWorkspacesNewGithubRoute
  '/_authenticated/workspaces/new/gitlab': typeof AuthenticatedWorkspacesNewGitlabRoute
  '/_authenticated/admin/catalog/': typeof AuthenticatedAdminCatalogIndexRoute
  '/_authenticated/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/_authenticated/workspaces/new/': typeof AuthenticatedWorkspacesNewIndexRoute
  '/_authenticated/admin/workspaces_/$workspaceSlug/users': typeof AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute
  '/_authenticated/w/$workspaceSlug/admin/audit': typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren
  '/_authenticated/w/$workspaceSlug/admin/members': typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  '/_authenticated/w/$workspaceSlug/admin/models': typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  '/_authenticated/w/$workspaceSlug/admin/onboarding': typeof AuthenticatedWWorkspaceSlugAdminOnboardingRoute
  '/_authenticated/w/$workspaceSlug/admin/practices': typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren
  '/_authenticated/w/$workspaceSlug/admin/settings': typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  '/_authenticated/w/$workspaceSlug/admin/teams': typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  '/_authenticated/w/$workspaceSlug/admin/usage': typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  '/_authenticated/w/$workspaceSlug/mentor/$threadId': typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  '/_authenticated/w/$workspaceSlug/mentor/': typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
  '/_authenticated/w/$workspaceSlug/reviews/': typeof AuthenticatedWWorkspaceSlugReviewsIndexRoute
  '/_authenticated/w/$workspaceSlug/teams/': typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/outline': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/scm': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/slack': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/releases': typeof AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/review': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/reviews': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteWithChildren
  '/_authenticated/w/$workspaceSlug/reviews/$artifactKind/$artifactId': typeof AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/': typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
  '/_authenticated/w/$workspaceSlug/user/$username/': typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/reviews/feedback': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/reviews/observations': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/reviews/runs': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute
  '/_authenticated/w/$workspaceSlug/user/$username/practice-groups/$groupSlug': typeof AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/reviews/': typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consent'
    | '/imprint'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/unsubscribe'
    | '/admin'
    | '/integrations'
    | '/settings'
    | '/auth/callback'
    | '/auth/error'
    | '/w/$workspaceSlug'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/feedback'
    | '/admin/login-providers'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/workspaces'
    | '/w/$workspaceSlug/login'
    | '/admin/'
    | '/w/$workspaceSlug/admin'
    | '/w/$workspaceSlug/activity'
    | '/w/$workspaceSlug/mentor'
    | '/w/$workspaceSlug/onboarding'
    | '/w/$workspaceSlug/practice-profile'
    | '/w/$workspaceSlug/reviews'
    | '/w/$workspaceSlug/workspace-activity'
    | '/workspaces/new/github'
    | '/workspaces/new/gitlab'
    | '/admin/catalog/'
    | '/w/$workspaceSlug/'
    | '/workspaces/new/'
    | '/admin/workspaces/$workspaceSlug/users'
    | '/w/$workspaceSlug/admin/audit'
    | '/w/$workspaceSlug/admin/integrations'
    | '/w/$workspaceSlug/admin/members'
    | '/w/$workspaceSlug/admin/models'
    | '/w/$workspaceSlug/admin/onboarding'
    | '/w/$workspaceSlug/admin/practices'
    | '/w/$workspaceSlug/admin/settings'
    | '/w/$workspaceSlug/admin/teams'
    | '/w/$workspaceSlug/admin/usage'
    | '/w/$workspaceSlug/mentor/$threadId'
    | '/w/$workspaceSlug/mentor/'
    | '/w/$workspaceSlug/reviews/'
    | '/w/$workspaceSlug/teams/'
    | '/w/$workspaceSlug/admin/integrations/outline'
    | '/w/$workspaceSlug/admin/integrations/scm'
    | '/w/$workspaceSlug/admin/integrations/slack'
    | '/w/$workspaceSlug/admin/practices/releases'
    | '/w/$workspaceSlug/admin/practices/review'
    | '/w/$workspaceSlug/admin/practices/reviews'
    | '/w/$workspaceSlug/reviews/$artifactKind/$artifactId'
    | '/w/$workspaceSlug/admin/integrations/'
    | '/w/$workspaceSlug/admin/practices/'
    | '/w/$workspaceSlug/user/$username/'
    | '/w/$workspaceSlug/admin/practices/reviews/feedback'
    | '/w/$workspaceSlug/admin/practices/reviews/observations'
    | '/w/$workspaceSlug/admin/practices/reviews/runs'
    | '/w/$workspaceSlug/user/$username/practice-groups/$groupSlug'
    | '/w/$workspaceSlug/admin/practices/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consent'
    | '/imprint'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/unsubscribe'
    | '/integrations'
    | '/settings'
    | '/auth/callback'
    | '/auth/error'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/login-providers'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/workspaces'
    | '/w/$workspaceSlug/login'
    | '/admin'
    | '/w/$workspaceSlug/admin'
    | '/w/$workspaceSlug/activity'
    | '/w/$workspaceSlug/onboarding'
    | '/w/$workspaceSlug/practice-profile'
    | '/w/$workspaceSlug/workspace-activity'
    | '/workspaces/new/github'
    | '/workspaces/new/gitlab'
    | '/admin/catalog'
    | '/w/$workspaceSlug'
    | '/workspaces/new'
    | '/admin/workspaces/$workspaceSlug/users'
    | '/w/$workspaceSlug/admin/audit'
    | '/w/$workspaceSlug/admin/members'
    | '/w/$workspaceSlug/admin/models'
    | '/w/$workspaceSlug/admin/onboarding'
    | '/w/$workspaceSlug/admin/settings'
    | '/w/$workspaceSlug/admin/teams'
    | '/w/$workspaceSlug/admin/usage'
    | '/w/$workspaceSlug/mentor/$threadId'
    | '/w/$workspaceSlug/mentor'
    | '/w/$workspaceSlug/reviews'
    | '/w/$workspaceSlug/teams'
    | '/w/$workspaceSlug/admin/integrations/outline'
    | '/w/$workspaceSlug/admin/integrations/scm'
    | '/w/$workspaceSlug/admin/integrations/slack'
    | '/w/$workspaceSlug/admin/practices/releases'
    | '/w/$workspaceSlug/admin/practices/review'
    | '/w/$workspaceSlug/reviews/$artifactKind/$artifactId'
    | '/w/$workspaceSlug/admin/integrations'
    | '/w/$workspaceSlug/admin/practices'
    | '/w/$workspaceSlug/user/$username'
    | '/w/$workspaceSlug/admin/practices/reviews/feedback'
    | '/w/$workspaceSlug/admin/practices/reviews/observations'
    | '/w/$workspaceSlug/admin/practices/reviews/runs'
    | '/w/$workspaceSlug/user/$username/practice-groups/$groupSlug'
    | '/w/$workspaceSlug/admin/practices/reviews'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/consent'
    | '/imprint'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/integrations'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/error'
    | '/_authenticated/w/$workspaceSlug'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/login-providers'
    | '/_authenticated/admin/models'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/surveys'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workspaces'
    | '/w/$workspaceSlug/login'
    | '/_authenticated/admin/'
    | '/_authenticated/w/$workspaceSlug/admin'
    | '/_authenticated/w/$workspaceSlug/activity'
    | '/_authenticated/w/$workspaceSlug/mentor'
    | '/_authenticated/w/$workspaceSlug/onboarding'
    | '/_authenticated/w/$workspaceSlug/practice-profile'
    | '/_authenticated/w/$workspaceSlug/reviews'
    | '/_authenticated/w/$workspaceSlug/workspace-activity'
    | '/_authenticated/workspaces/new/github'
    | '/_authenticated/workspaces/new/gitlab'
    | '/_authenticated/admin/catalog/'
    | '/_authenticated/w/$workspaceSlug/'
    | '/_authenticated/workspaces/new/'
    | '/_authenticated/admin/workspaces_/$workspaceSlug/users'
    | '/_authenticated/w/$workspaceSlug/admin/audit'
    | '/_authenticated/w/$workspaceSlug/admin/integrations'
    | '/_authenticated/w/$workspaceSlug/admin/members'
    | '/_authenticated/w/$workspaceSlug/admin/models'
    | '/_authenticated/w/$workspaceSlug/admin/onboarding'
    | '/_authenticated/w/$workspaceSlug/admin/practices'
    | '/_authenticated/w/$workspaceSlug/admin/settings'
    | '/_authenticated/w/$workspaceSlug/admin/teams'
    | '/_authenticated/w/$workspaceSlug/admin/usage'
    | '/_authenticated/w/$workspaceSlug/mentor/$threadId'
    | '/_authenticated/w/$workspaceSlug/mentor/'
    | '/_authenticated/w/$workspaceSlug/reviews/'
    | '/_authenticated/w/$workspaceSlug/teams/'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/outline'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/scm'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/slack'
    | '/_authenticated/w/$workspaceSlug/admin/practices/releases'
    | '/_authenticated/w/$workspaceSlug/admin/practices/review'
    | '/_authenticated/w/$workspaceSlug/admin/practices/reviews'
    | '/_authenticated/w/$workspaceSlug/reviews/$artifactKind/$artifactId'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/'
    | '/_authenticated/w/$workspaceSlug/admin/practices/'
    | '/_authenticated/w/$workspaceSlug/user/$username/'
    | '/_authenticated/w/$workspaceSlug/admin/practices/reviews/feedback'
    | '/_authenticated/w/$workspaceSlug/admin/practices/reviews/observations'
    | '/_authenticated/w/$workspaceSlug/admin/practices/reviews/runs'
    | '/_authenticated/w/$workspaceSlug/user/$username/practice-groups/$groupSlug'
    | '/_authenticated/w/$workspaceSlug/admin/practices/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ConsentRoute: typeof ConsentRoute
  ImprintRoute: typeof ImprintRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  WWorkspaceSlugLoginRoute: typeof WWorkspaceSlugLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/login-providers': {
      id: '/_authenticated/admin/login-providers'
      path: '/login-providers'
      fullPath: '/admin/login-providers'
      preLoaderRoute: typeof AuthenticatedAdminLoginProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/models': {
      id: '/_authenticated/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AuthenticatedAdminModelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/surveys': {
      id: '/_authenticated/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AuthenticatedAdminSurveysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/workspaces': {
      id: '/_authenticated/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/w/$workspaceSlug': {
      id: '/_authenticated/w/$workspaceSlug'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/w/$workspaceSlug/login': {
      id: '/w/$workspaceSlug/login'
      path: '/w/$workspaceSlug/login'
      fullPath: '/w/$workspaceSlug/login'
      preLoaderRoute: typeof WWorkspaceSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/catalog/': {
      id: '/_authenticated/admin/catalog/'
      path: '/'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogRoute
    }
    '/_authenticated/w/$workspaceSlug/': {
      id: '/_authenticated/w/$workspaceSlug/'
      path: '/'
      fullPath: '/w/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/activity': {
      id: '/_authenticated/w/$workspaceSlug/activity'
      path: '/activity'
      fullPath: '/w/$workspaceSlug/activity'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugActivityRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin': {
      id: '/_authenticated/w/$workspaceSlug/admin'
      path: '/admin'
      fullPath: '/w/$workspaceSlug/admin'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/mentor': {
      id: '/_authenticated/w/$workspaceSlug/mentor'
      path: '/mentor'
      fullPath: '/w/$workspaceSlug/mentor'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugMentorRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/onboarding': {
      id: '/_authenticated/w/$workspaceSlug/onboarding'
      path: '/onboarding'
      fullPath: '/w/$workspaceSlug/onboarding'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugOnboardingRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/practice-profile': {
      id: '/_authenticated/w/$workspaceSlug/practice-profile'
      path: '/practice-profile'
      fullPath: '/w/$workspaceSlug/practice-profile'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugPracticeProfileRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/reviews': {
      id: '/_authenticated/w/$workspaceSlug/reviews'
      path: '/reviews'
      fullPath: '/w/$workspaceSlug/reviews'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugReviewsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/workspace-activity': {
      id: '/_authenticated/w/$workspaceSlug/workspace-activity'
      path: '/workspace-activity'
      fullPath: '/w/$workspaceSlug/workspace-activity'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugWorkspaceActivityRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/new/': {
      id: '/_authenticated/workspaces/new/'
      path: '/workspaces/new'
      fullPath: '/workspaces/new/'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/new/github': {
      id: '/_authenticated/workspaces/new/github'
      path: '/workspaces/new/github'
      fullPath: '/workspaces/new/github'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewGithubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/new/gitlab': {
      id: '/_authenticated/workspaces/new/gitlab'
      path: '/workspaces/new/gitlab'
      fullPath: '/workspaces/new/gitlab'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewGitlabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workspaces_/$workspaceSlug/users': {
      id: '/_authenticated/admin/workspaces_/$workspaceSlug/users'
      path: '/workspaces/$workspaceSlug/users'
      fullPath: '/admin/workspaces/$workspaceSlug/users'
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesWorkspaceSlugUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/audit': {
      id: '/_authenticated/w/$workspaceSlug/admin/audit'
      path: '/audit'
      fullPath: '/w/$workspaceSlug/admin/audit'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminAuditRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations'
      path: '/integrations'
      fullPath: '/w/$workspaceSlug/admin/integrations'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/members': {
      id: '/_authenticated/w/$workspaceSlug/admin/members'
      path: '/members'
      fullPath: '/w/$workspaceSlug/admin/members'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminMembersRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/models': {
      id: '/_authenticated/w/$workspaceSlug/admin/models'
      path: '/models'
      fullPath: '/w/$workspaceSlug/admin/models'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminModelsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/onboarding': {
      id: '/_authenticated/w/$workspaceSlug/admin/onboarding'
      path: '/onboarding'
      fullPath: '/w/$workspaceSlug/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices'
      path: '/practices'
      fullPath: '/w/$workspaceSlug/admin/practices'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/settings': {
      id: '/_authenticated/w/$workspaceSlug/admin/settings'
      path: '/settings'
      fullPath: '/w/$workspaceSlug/admin/settings'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/teams': {
      id: '/_authenticated/w/$workspaceSlug/admin/teams'
      path: '/teams'
      fullPath: '/w/$workspaceSlug/admin/teams'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/usage': {
      id: '/_authenticated/w/$workspaceSlug/admin/usage'
      path: '/usage'
      fullPath: '/w/$workspaceSlug/admin/usage'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminUsageRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/mentor/': {
      id: '/_authenticated/w/$workspaceSlug/mentor/'
      path: '/'
      fullPath: '/w/$workspaceSlug/mentor/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugMentorIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugMentorRoute
    }
    '/_authenticated/w/$workspaceSlug/mentor/$threadId': {
      id: '/_authenticated/w/$workspaceSlug/mentor/$threadId'
      path: '/$threadId'
      fullPath: '/w/$workspaceSlug/mentor/$threadId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugMentorThreadIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugMentorRoute
    }
    '/_authenticated/w/$workspaceSlug/reviews/': {
      id: '/_authenticated/w/$workspaceSlug/reviews/'
      path: '/'
      fullPath: '/w/$workspaceSlug/reviews/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugReviewsRoute
    }
    '/_authenticated/w/$workspaceSlug/teams/': {
      id: '/_authenticated/w/$workspaceSlug/teams/'
      path: '/teams'
      fullPath: '/w/$workspaceSlug/teams/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/'
      path: '/'
      fullPath: '/w/$workspaceSlug/admin/integrations/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/outline': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/outline'
      path: '/outline'
      fullPath: '/w/$workspaceSlug/admin/integrations/outline'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/scm': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/scm'
      path: '/scm'
      fullPath: '/w/$workspaceSlug/admin/integrations/scm'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/slack': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/slack'
      path: '/slack'
      fullPath: '/w/$workspaceSlug/admin/integrations/slack'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/'
      path: '/'
      fullPath: '/w/$workspaceSlug/admin/practices/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/releases': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/releases'
      path: '/releases'
      fullPath: '/w/$workspaceSlug/admin/practices/releases'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReleasesRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/review': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/review'
      path: '/review'
      fullPath: '/w/$workspaceSlug/admin/practices/review'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/reviews': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/reviews'
      path: '/reviews'
      fullPath: '/w/$workspaceSlug/admin/practices/reviews'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/reviews/$artifactKind/$artifactId': {
      id: '/_authenticated/w/$workspaceSlug/reviews/$artifactKind/$artifactId'
      path: '/$artifactKind/$artifactId'
      fullPath: '/w/$workspaceSlug/reviews/$artifactKind/$artifactId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugReviewsRoute
    }
    '/_authenticated/w/$workspaceSlug/user/$username/': {
      id: '/_authenticated/w/$workspaceSlug/user/$username/'
      path: '/user/$username'
      fullPath: '/w/$workspaceSlug/user/$username/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/reviews/': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/reviews/'
      path: '/'
      fullPath: '/w/$workspaceSlug/admin/practices/reviews/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/reviews/feedback': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/reviews/feedback'
      path: '/feedback'
      fullPath: '/w/$workspaceSlug/admin/practices/reviews/feedback'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/reviews/observations': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/reviews/observations'
      path: '/observations'
      fullPath: '/w/$workspaceSlug/admin/practices/reviews/observations'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/reviews/runs': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/reviews/runs'
      path: '/runs'
      fullPath: '/w/$workspaceSlug/admin/practices/reviews/runs'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute
    }
    '/_authenticated/w/$workspaceSlug/user/$username/practice-groups/$groupSlug': {
      id: '/_authenticated/w/$workspaceSlug/user/$username/practice-groups/$groupSlug'
      path: '/user/$username/practice-groups/$groupSlug'
      fullPath: '/w/$workspaceSlug/user/$username/practice-groups/$groupSlug'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
  }
}

interface AuthenticatedAdminCatalogRouteChildren {
  AuthenticatedAdminCatalogIndexRoute: typeof AuthenticatedAdminCatalogIndexRoute
}

const AuthenticatedAdminCatalogRouteChildren: AuthenticatedAdminCatalogRouteChildren =
  {
    AuthenticatedAdminCatalogIndexRoute: AuthenticatedAdminCatalogIndexRoute,
  }

const AuthenticatedAdminCatalogRouteWithChildren =
  AuthenticatedAdminCatalogRoute._addFileChildren(
    AuthenticatedAdminCatalogRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRouteWithChildren
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminLoginProvidersRoute: typeof AuthenticatedAdminLoginProvidersRoute
  AuthenticatedAdminModelsRoute: typeof AuthenticatedAdminModelsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSurveysRoute: typeof AuthenticatedAdminSurveysRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkspacesRoute: typeof AuthenticatedAdminWorkspacesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute: typeof AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRouteWithChildren,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminLoginProvidersRoute: AuthenticatedAdminLoginProvidersRoute,
  AuthenticatedAdminModelsRoute: AuthenticatedAdminModelsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSurveysRoute: AuthenticatedAdminSurveysRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkspacesRoute: AuthenticatedAdminWorkspacesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute:
    AuthenticatedAdminWorkspacesWorkspaceSlugUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren {
  AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
}

const AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren: AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute,
  }

const AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminIntegrationsRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteChildren {
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute
}

const AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteChildren: AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReviewsFeedbackRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReviewsObservationsRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReviewsRunsRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReviewsIndexRoute,
  }

const AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren {
  AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute
  AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute
  AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteWithChildren
  AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
}

const AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren: AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReleasesRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReviewRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesReviewsRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesReviewsRouteWithChildren,
    AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute,
  }

const AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminPracticesRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugAdminRouteRouteChildren {
  AuthenticatedWWorkspaceSlugAdminAuditRoute: typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren
  AuthenticatedWWorkspaceSlugAdminMembersRoute: typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  AuthenticatedWWorkspaceSlugAdminModelsRoute: typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  AuthenticatedWWorkspaceSlugAdminOnboardingRoute: typeof AuthenticatedWWorkspaceSlugAdminOnboardingRoute
  AuthenticatedWWorkspaceSlugAdminPracticesRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren
  AuthenticatedWWorkspaceSlugAdminSettingsRoute: typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  AuthenticatedWWorkspaceSlugAdminTeamsRoute: typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  AuthenticatedWWorkspaceSlugAdminUsageRoute: typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
}

const AuthenticatedWWorkspaceSlugAdminRouteRouteChildren: AuthenticatedWWorkspaceSlugAdminRouteRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminAuditRoute:
      AuthenticatedWWorkspaceSlugAdminAuditRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren,
    AuthenticatedWWorkspaceSlugAdminMembersRoute:
      AuthenticatedWWorkspaceSlugAdminMembersRoute,
    AuthenticatedWWorkspaceSlugAdminModelsRoute:
      AuthenticatedWWorkspaceSlugAdminModelsRoute,
    AuthenticatedWWorkspaceSlugAdminOnboardingRoute:
      AuthenticatedWWorkspaceSlugAdminOnboardingRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren,
    AuthenticatedWWorkspaceSlugAdminSettingsRoute:
      AuthenticatedWWorkspaceSlugAdminSettingsRoute,
    AuthenticatedWWorkspaceSlugAdminTeamsRoute:
      AuthenticatedWWorkspaceSlugAdminTeamsRoute,
    AuthenticatedWWorkspaceSlugAdminUsageRoute:
      AuthenticatedWWorkspaceSlugAdminUsageRoute,
  }

const AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminRouteRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminRouteRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugMentorRouteChildren {
  AuthenticatedWWorkspaceSlugMentorThreadIdRoute: typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  AuthenticatedWWorkspaceSlugMentorIndexRoute: typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
}

const AuthenticatedWWorkspaceSlugMentorRouteChildren: AuthenticatedWWorkspaceSlugMentorRouteChildren =
  {
    AuthenticatedWWorkspaceSlugMentorThreadIdRoute:
      AuthenticatedWWorkspaceSlugMentorThreadIdRoute,
    AuthenticatedWWorkspaceSlugMentorIndexRoute:
      AuthenticatedWWorkspaceSlugMentorIndexRoute,
  }

const AuthenticatedWWorkspaceSlugMentorRouteWithChildren =
  AuthenticatedWWorkspaceSlugMentorRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugMentorRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugReviewsRouteChildren {
  AuthenticatedWWorkspaceSlugReviewsIndexRoute: typeof AuthenticatedWWorkspaceSlugReviewsIndexRoute
  AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute: typeof AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute
}

const AuthenticatedWWorkspaceSlugReviewsRouteChildren: AuthenticatedWWorkspaceSlugReviewsRouteChildren =
  {
    AuthenticatedWWorkspaceSlugReviewsIndexRoute:
      AuthenticatedWWorkspaceSlugReviewsIndexRoute,
    AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute:
      AuthenticatedWWorkspaceSlugReviewsArtifactKindArtifactIdRoute,
  }

const AuthenticatedWWorkspaceSlugReviewsRouteWithChildren =
  AuthenticatedWWorkspaceSlugReviewsRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugReviewsRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugRouteRouteChildren {
  AuthenticatedWWorkspaceSlugAdminRouteRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  AuthenticatedWWorkspaceSlugActivityRoute: typeof AuthenticatedWWorkspaceSlugActivityRoute
  AuthenticatedWWorkspaceSlugMentorRoute: typeof AuthenticatedWWorkspaceSlugMentorRouteWithChildren
  AuthenticatedWWorkspaceSlugOnboardingRoute: typeof AuthenticatedWWorkspaceSlugOnboardingRoute
  AuthenticatedWWorkspaceSlugPracticeProfileRoute: typeof AuthenticatedWWorkspaceSlugPracticeProfileRoute
  AuthenticatedWWorkspaceSlugReviewsRoute: typeof AuthenticatedWWorkspaceSlugReviewsRouteWithChildren
  AuthenticatedWWorkspaceSlugWorkspaceActivityRoute: typeof AuthenticatedWWorkspaceSlugWorkspaceActivityRoute
  AuthenticatedWWorkspaceSlugIndexRoute: typeof AuthenticatedWWorkspaceSlugIndexRoute
  AuthenticatedWWorkspaceSlugTeamsIndexRoute: typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  AuthenticatedWWorkspaceSlugUserUsernameIndexRoute: typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
  AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute: typeof AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute
}

const AuthenticatedWWorkspaceSlugRouteRouteChildren: AuthenticatedWWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminRouteRoute:
      AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren,
    AuthenticatedWWorkspaceSlugActivityRoute:
      AuthenticatedWWorkspaceSlugActivityRoute,
    AuthenticatedWWorkspaceSlugMentorRoute:
      AuthenticatedWWorkspaceSlugMentorRouteWithChildren,
    AuthenticatedWWorkspaceSlugOnboardingRoute:
      AuthenticatedWWorkspaceSlugOnboardingRoute,
    AuthenticatedWWorkspaceSlugPracticeProfileRoute:
      AuthenticatedWWorkspaceSlugPracticeProfileRoute,
    AuthenticatedWWorkspaceSlugReviewsRoute:
      AuthenticatedWWorkspaceSlugReviewsRouteWithChildren,
    AuthenticatedWWorkspaceSlugWorkspaceActivityRoute:
      AuthenticatedWWorkspaceSlugWorkspaceActivityRoute,
    AuthenticatedWWorkspaceSlugIndexRoute:
      AuthenticatedWWorkspaceSlugIndexRoute,
    AuthenticatedWWorkspaceSlugTeamsIndexRoute:
      AuthenticatedWWorkspaceSlugTeamsIndexRoute,
    AuthenticatedWWorkspaceSlugUserUsernameIndexRoute:
      AuthenticatedWWorkspaceSlugUserUsernameIndexRoute,
    AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute:
      AuthenticatedWWorkspaceSlugUserUsernamePracticeGroupsGroupSlugRoute,
  }

const AuthenticatedWWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedWWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWWorkspaceSlugRouteRoute: typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  AuthenticatedWorkspacesNewGithubRoute: typeof AuthenticatedWorkspacesNewGithubRoute
  AuthenticatedWorkspacesNewGitlabRoute: typeof AuthenticatedWorkspacesNewGitlabRoute
  AuthenticatedWorkspacesNewIndexRoute: typeof AuthenticatedWorkspacesNewIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWWorkspaceSlugRouteRoute:
    AuthenticatedWWorkspaceSlugRouteRouteWithChildren,
  AuthenticatedWorkspacesNewGithubRoute: AuthenticatedWorkspacesNewGithubRoute,
  AuthenticatedWorkspacesNewGitlabRoute: AuthenticatedWorkspacesNewGitlabRoute,
  AuthenticatedWorkspacesNewIndexRoute: AuthenticatedWorkspacesNewIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ConsentRoute: ConsentRoute,
  ImprintRoute: ImprintRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  WWorkspaceSlugLoginRoute: WWorkspaceSlugLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
