package de.tum.cit.aet.hephaestus.core.tenancy;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import de.tum.cit.aet.hephaestus.core.LoggingUtils;
import io.micrometer.core.instrument.Counter;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.hibernate.resource.jdbc.spi.StatementInspector;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Hibernate {@link StatementInspector} that asserts every SQL statement against a
 * workspace-scoped table carries a {@code workspace_id} predicate.
 *
 * <p>Pipeline (cheapest checks first):
 * <ol>
 *   <li>Active bypass on the thread ({@code @WorkspaceAgnostic}) — pass</li>
 *   <li>Mode {@link TenancyEnforcement#OFF} — pass</li>
 *   <li>Caffeine cache hit on the literal SQL — return cached decision</li>
 *   <li>Word-boundary regex: {@code workspace_id} mentioned anywhere — pass</li>
 *   <li>Table-extract regex: pull table names from {@code FROM/JOIN/UPDATE/INTO} clauses,
 *       intersect with {@link WorkspaceScopedTables#scopedTables()}. Any match without
 *       a {@code workspace_id} reference anywhere in the statement is a violation.</li>
 * </ol>
 *
 * <p><b>Why regex, not a SQL parser?</b> JSqlParser was tried and rejected: adding it to
 * the classpath caused Spring Data JPA to auto-activate its {@code JSqlParserQueryEnhancer},
 * which fails on legitimate Postgres-escaped {@code @Query} natives (e.g.,
 * {@code CONCAT(:id\:\:text, ...)}), breaking application boot. A regex-only inspector
 * has no transitive blast radius and is sufficient for the {@code workspace_id} predicate
 * shape we actually care about.
 *
 * <p>Wired via Spring Boot's {@code HibernatePropertiesCustomizer} in
 * {@link TenancyConfiguration}.
 */
public class WorkspaceStatementInspector implements StatementInspector {

    private static final Logger log = LoggerFactory.getLogger(WorkspaceStatementInspector.class);

    /**
     * Matches the {@code workspace_id} column as a word boundary. Tolerates every
     * predicate shape Hibernate emits (simple {@code col = ?}, tuple-IN
     * {@code (a, workspace_id) IN ((?, ?))}, schema-qualified
     * {@code wm1_0.workspace_id}, etc.). Trade-off: a literal string containing the
     * bare word would falsely pass. Acceptable because Hibernate-emitted SQL is
     * parameterized — column names rarely appear inside string-literal values — and
     * the alternative (tighter predicate matching) breaks legitimate composite-key
     * queries.
     */
    private static final Pattern WORKSPACE_ID_PATTERN = Pattern.compile("\\bworkspace_id\\b", Pattern.CASE_INSENSITIVE);

    /**
     * Extracts table identifiers immediately following {@code FROM}, {@code JOIN}, or
     * {@code UPDATE}. Captures the optional schema-qualified name; {@link #unqualify(String)}
     * strips the schema afterwards. Designed to tolerate Hibernate-emitted SQL,
     * Postgres-quoted identifiers, and common edge cases without invoking a grammar-based
     * parser.
     *
     * <p><b>{@code INTO} intentionally excluded:</b> {@code INSERT INTO} cannot leak data
     * across workspaces — creating a row is not a read. Including it forced every entity
     * scoped indirectly (via FK to a parent that owns {@code workspace_id}, e.g.
     * {@code observation → practice}) to be marked {@code @WorkspaceAgnostic} just so
     * Hibernate's autogenerated INSERTs could run. Filtering INSERT out at the regex layer
     * keeps the security control focused on the actual threat model (read leakage) while
     * shedding a large class of false positives.
     *
     * <p><b>Old-style comma joins out of scope:</b> only the first table of a
     * {@code FROM a, scoped_b} list is captured — the trailing {@code scoped_b} escapes. This is a
     * deliberate regex-vs-parser tradeoff: a comma-split would have to tell a FROM-list comma apart
     * from SELECT-list / function-arg commas, reintroducing exactly the false-positive class that made
     * us reject JSqlParser. Hibernate never emits comma joins (it always uses explicit {@code JOIN}), so
     * the gap is only reachable via hand-written native SQL, which should carry {@code workspace_id}
     * explicitly anyway.
     */
    private static final Pattern TABLE_REFERENCE_PATTERN = Pattern.compile(
            "(?:\\bFROM\\b|\\bJOIN\\b|\\bUPDATE\\b)\\s+(\"?[A-Za-z_][A-Za-z0-9_]*\"?(?:\\s*\\.\\s*\"?[A-Za-z_][A-Za-z0-9_]*\"?)?)",
            Pattern.CASE_INSENSITIVE);

    /** One surrogate-key predicate: {@code id = ?} or {@code <anything>_id = ?}, optionally quoted. */
    private static final String KEY_EQUALS_PARAMETER = "\"?(?:id|[A-Za-z_][A-Za-z0-9_]*_id)\"?\\s*=\\s*\\?";

    /**
     * Matches Hibernate-emitted DML on a single row identified solely by primary key —
     * {@code DELETE FROM table WHERE id = ?} or
     * {@code UPDATE table SET ... WHERE id = ?} (no other predicate columns).
     *
     * <p>These are tenancy-safe by construction: the row was already loaded into the
     * persistence context within a workspace-checked transaction, and the surrogate {@code id}
     * uniquely identifies it. Allowing this pattern aligns with how Spring Data
     * {@code delete(entity)}/{@code save(entity)} synthesise SQL, without requiring every
     * scoped repository to wear {@code @WorkspaceAgnostic} just to satisfy the inspector.
     *
     * <p>The pattern is intentionally narrow: any additional condition (e.g.
     * {@code WHERE id = ? AND something_else}) breaks the match and falls through to the
     * standard {@code workspace_id} check, preserving enforcement for hand-written queries.
     */
    private static final Pattern PK_ONLY_DML_PATTERN = Pattern.compile(
            "^\\s*(?:DELETE\\s+FROM|UPDATE)\\s+\"?[A-Za-z_][A-Za-z0-9_]*\"?" + "(?:\\s+SET\\s+.+?)?"
                    + "\\s+WHERE\\s+" + KEY_EQUALS_PARAMETER
                    +
                    // Optional @Version optimistic-lock predicate: AND version = ?
                    "(?:\\s+AND\\s+\"?version\"?\\s*=\\s*\\?)?"
                    + "\\s*$",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    /**
     * Matches the one statement Hibernate emits to remove an element of a {@code @ManyToMany}:
     * the join-table row deleted by both of its foreign keys,
     * {@code DELETE FROM issue_label WHERE issue_id = ? AND label_id = ?}. Fully anchored, DELETE
     * only, exactly two key predicates, so neither a comment nor a SET clause can hide anything
     * in it. Which tables it may apply to is not a naming convention: the captured table must be
     * a many-to-many join table in the mapping metamodel, so an entity table with two
     * {@code *_id} columns never qualifies however it is named.
     */
    private static final Pattern JOIN_TABLE_ROW_DELETE_PATTERN = Pattern.compile(
            "^\\s*DELETE\\s+FROM\\s+\"?([A-Za-z_][A-Za-z0-9_]*)\"?\\s+WHERE\\s+"
                    + "\"?([A-Za-z_][A-Za-z0-9_]*_id)\"?\\s*=\\s*\\?\\s+AND\\s+"
                    + "\"?([A-Za-z_][A-Za-z0-9_]*_id)\"?\\s*=\\s*\\?\\s*$",
            Pattern.CASE_INSENSITIVE);

    /**
     * The shape of a single-row DML whose WHERE clause might be a complete primary key:
     * {@code UPDATE table SET ... WHERE <conjunction>} or {@code DELETE FROM table WHERE
     * <conjunction>}. The conjunction is captured whole rather than matched column by column,
     * because whether it covers the key is a question for the mapping metamodel, not for a regex —
     * {@link #coversCompletePrimaryKey} answers it.
     */
    private static final Pattern FULL_KEY_DML_PATTERN = Pattern.compile(
            "^\\s*(?:DELETE\\s+FROM|UPDATE)\\s+\"?([A-Za-z_][A-Za-z0-9_]*)\"?"
                    // Captured, not skipped: what a SET assigns reaches as far as what a WHERE
                    // selects, and it is checked below.
                    + "(?:\\s+SET\\s+(.+?))?"
                    // Greedy to the end, trimmed in Java. A reluctant tail against a trailing
                    // `\\s*$` retries at every end position, which a long whitespace run makes
                    // quadratic.
                    + "\\s+WHERE\\s+(.+)$",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    /**
     * What disqualifies a statement from this allowance before its key is even considered.
     *
     * <p>A comment marker means the text read here as a WHERE clause may not be one the database
     * will apply: {@code UPDATE t SET c=?} followed by a newline and {@code -- WHERE k=?} parses
     * here as a keyed update and arrives at PostgreSQL as an unrestricted one. A second table
     * reference means the statement reads rows this rule never examined — a subquery in a SET
     * assignment copies another workspace's data into the row the key names. A separator means
     * there is more than one statement to account for.
     */
    private static final Pattern SMUGGLED_CLAUSE_PATTERN =
            Pattern.compile("--|/\\*|;|\\bSELECT\\b|\\bFROM\\b|\\bJOIN\\b", Pattern.CASE_INSENSITIVE);

    /**
     * The fast path declines to parse a statement longer than the ORM has reason to emit, bounding
     * what the reluctant SET match can cost. Declining is the safe answer — the standard
     * {@code workspace_id} check still runs.
     */
    private static final int FAST_PATH_SQL_LIMIT = 8192;

    /** One conjunct of that WHERE clause, and the only shape allowed in it: {@code column = ?}. */
    private static final Pattern KEY_PREDICATE_PATTERN =
            Pattern.compile("^\\s*\"?([A-Za-z_][A-Za-z0-9_]*)\"?\\s*=\\s*\\?\\s*$");

    private static final Pattern AND_SPLIT_PATTERN = Pattern.compile("\\s+AND\\s+", Pattern.CASE_INSENSITIVE);

    /** Hibernate's optimistic-lock predicate, which rides along with the key on a versioned entity. */
    private static final String VERSION_COLUMN = "version";

    /**
     * Matches a Hibernate-emitted load that pins the result set to a single row (or a
     * parent-FK-bounded set) via a surrogate-key predicate. Three concrete shapes:
     * <ul>
     *   <li>{@code EntityManager.find(Class, id)} / lazy {@code @ManyToOne} fetch →
     *       {@code FROM table alias … WHERE alias.id = ?}</li>
     *   <li>Single-table inheritance load by id →
     *       {@code FROM table alias … WHERE alias.id = ? AND alias.<discriminator> = ?}
     *       (or the discriminator appears first).</li>
     *   <li>Lazy {@code @OneToMany}/{@code @ManyToMany} collection initialisation →
     *       {@code FROM join_or_child_table alias … WHERE alias.<parent>_id = ?}</li>
     *   <li>That same initialisation under {@code @BatchSize}, where Hibernate fills several
     *       parents' collections in one round trip →
     *       {@code FROM child_table alias … WHERE alias.<parent>_id = ANY(?)}</li>
     * </ul>
     *
     * <p>Safe by construction: the caller already had the surrogate key — or, in the batched form,
     * every key in the bound array, each obtained the same way. {@code ANY(?)} takes a single array
     * parameter, so the predicate stays pinned to those keys. Surrogate keys are
     * opaque to URL inputs and only come into existence via a workspace-scoped path
     * ({@code findByWorkspaceIdAndSlug} → {@code entity.getRelation()} → lazy fetch).
     *
     * <p>The check requires {@code SELECT … FROM <one-table> <alias>} (alias capture) and a
     * WHERE clause containing {@code <alias>.<id|*_id> = ?}. The WHERE may contain
     * additional conjunctive predicates (discriminators, soft-delete filters), but the
     * shape stays anchored to the captured alias — leaking across workspaces would require
     * dropping the alias-PK predicate entirely.
     */
    private static final Pattern PK_ONLY_SELECT_PATTERN = Pattern.compile(
            "^\\s*SELECT\\b.+?\\bFROM\\s+\"?[A-Za-z_][A-Za-z0-9_]*\"?\\s+([A-Za-z_][A-Za-z0-9_]*)\\b" + ".*?"
                    + "\\bWHERE\\b"
                    + ".*?"
                    + "\\b\\1\\s*\\.\\s*\"?(?:id|[A-Za-z_][A-Za-z0-9_]*_id)\"?\\s*=\\s*(?:\\?|ANY\\s*\\(\\s*\\?\\s*\\))"
                    + ".*?$",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    /** Identifies INSERTs cheaply without anchoring to whitespace shape. */
    private static final Pattern INSERT_STATEMENT_PATTERN =
            Pattern.compile("^\\s*INSERT\\s+INTO\\b", Pattern.CASE_INSENSITIVE);

    /**
     * A standalone {@code OR} token. The PK-only fast paths anchor on a single
     * {@code <alias>.id = ?} predicate but otherwise tolerate trailing/leading {@code .*?},
     * so {@code WHERE id = ? OR is_public = true} would otherwise satisfy the pattern while
     * actually broadening the result set well past the single keyed row — defeating the
     * "already had the surrogate key" safety argument. A disjunction therefore disqualifies the
     * fast path and forces the standard {@code workspace_id} check. Hibernate never emits a
     * disjunctive PK load, so this only over-reports on exotic hand-written SQL (the safe
     * direction). Word-boundary so identifiers like {@code coordinator} don't trip it.
     */
    private static final Pattern OR_TOKEN_PATTERN = Pattern.compile("\\bOR\\b", Pattern.CASE_INSENSITIVE);

    private final WorkspaceScopedTables scopedTables;
    private final TenancyEnforcement mode;
    private final TenancyViolationReporter reporter;
    private final Counter parseFailureCounter;

    private final Cache<String, Decision> decisionCache =
            Caffeine.newBuilder().maximumSize(10_000).build();

    public WorkspaceStatementInspector(
            WorkspaceScopedTables scopedTables,
            TenancyEnforcement mode,
            TenancyViolationReporter reporter,
            Counter parseFailureCounter) {
        this.scopedTables = scopedTables;
        this.mode = mode;
        this.reporter = reporter;
        this.parseFailureCounter = parseFailureCounter;
    }

    @Override
    public @Nullable String inspect(@Nullable String sql) {
        if (sql == null || sql.isBlank()) return sql;
        if (mode == TenancyEnforcement.OFF) return sql;
        if (TenancyBypass.isActive()) return sql;

        Decision decision = decisionCache.get(sql, this::analyze);
        if (decision != null && decision.violated()) {
            reporter.report(sql, decision.unguardedTables(), mode);
        }
        return sql;
    }

    /**
     * True iff {@code sql} is single-row DML whose WHERE clause is a conjunction of {@code column =
     * ?} predicates covering exactly the table's primary key — no more columns and no fewer.
     *
     * <p>Every way of being unsure is a {@code false}: an unknown table (the metamodel is not
     * populated until {@link org.springframework.boot.context.event.ApplicationReadyEvent}), a
     * conjunct that is anything but {@code column = ?}, a disjunction, a repeated column, or a
     * column set that is not the key. The statement then falls through to the standard
     * {@code workspace_id} check, so this can only ever narrow what is reported, never widen it.
     */
    private boolean coversCompletePrimaryKey(String sql) {
        if (sql.length() > FAST_PATH_SQL_LIMIT) return false;
        Matcher dml = FULL_KEY_DML_PATTERN.matcher(sql);
        if (!dml.matches()) return false;
        // An OR anywhere would reach rows the key does not name.
        if (OR_TOKEN_PATTERN.matcher(sql).find()) return false;

        String setClause = dml.group(2);
        String whereClause = dml.group(3).strip();
        if (setClause != null && SMUGGLED_CLAUSE_PATTERN.matcher(setClause).find()) return false;
        if (SMUGGLED_CLAUSE_PATTERN.matcher(whereClause).find()) return false;

        Set<String> keyColumns = scopedTables.primaryKeyColumns(unqualify(dml.group(1)));
        if (keyColumns.isEmpty()) return false;

        Set<String> predicateColumns = new HashSet<>();
        for (String conjunct : AND_SPLIT_PATTERN.split(whereClause)) {
            Matcher predicate = KEY_PREDICATE_PATTERN.matcher(conjunct);
            if (!predicate.matches()) return false;
            String column = predicate.group(1).toLowerCase(Locale.ROOT);
            // `version = ?` is the optimistic lock, not part of the key — unless this table really
            // does key on a column of that name, in which case it counts as the key column it is.
            if (VERSION_COLUMN.equals(column) && !keyColumns.contains(column)) continue;
            if (!predicateColumns.add(column)) return false;
        }
        return predicateColumns.equals(keyColumns);
    }

    private Decision analyze(String sql) {
        // INSERTs cannot leak data across workspaces — they create new rows.
        if (INSERT_STATEMENT_PATTERN.matcher(sql).find()) {
            return Decision.ok();
        }
        // Hibernate-emitted single-row PK DML is safe: the row was already loaded
        // within a workspace-checked scope and identified by a surrogate primary key.
        if (PK_ONLY_DML_PATTERN.matcher(sql).matches()) {
            return Decision.ok();
        }
        // The same reasoning as PK_ONLY_DML above, for a composite key: a WHERE clause that is
        // exactly the table's whole primary key names at most one row, and the caller had to hold
        // that row's full identity to write it. Hibernate emits this for every @EmbeddedId
        // association entity — `UPDATE repository_collaborator SET permission=? WHERE
        // repository_id=? AND "user_id"=?` — which the single-key pattern above cannot match, and
        // which is not a @ManyToMany join table so the join-table rule below does not cover it
        // either. The key comes from the mapping metamodel, never from a naming convention.
        if (coversCompletePrimaryKey(sql)) {
            return Decision.ok();
        }
        Matcher joinTableRowDelete = JOIN_TABLE_ROW_DELETE_PATTERN.matcher(sql);
        if (joinTableRowDelete.matches()
                // Two different foreign keys: the row's whole key, not one key named twice.
                && !joinTableRowDelete.group(2).equalsIgnoreCase(joinTableRowDelete.group(3))
                && scopedTables.isManyToManyJoinTable(unqualify(joinTableRowDelete.group(1)))) {
            return Decision.ok();
        }
        // Hibernate-emitted entity load / lazy-fetch by PK is safe for the same reason —
        // the caller already had the primary key. A disjunction (OR) would broaden the result
        // set past the single keyed row, so it disqualifies the fast path.
        if (PK_ONLY_SELECT_PATTERN.matcher(sql).matches()
                && !OR_TOKEN_PATTERN.matcher(sql).find()) {
            return Decision.ok();
        }
        if (WORKSPACE_ID_PATTERN.matcher(sql).find()) {
            return Decision.ok();
        }
        try {
            Set<String> unguarded = new HashSet<>();
            Matcher matcher = TABLE_REFERENCE_PATTERN.matcher(sql);
            while (matcher.find()) {
                String name = unqualify(matcher.group(1)).toLowerCase(Locale.ROOT);
                if (scopedTables.isScoped(name)) {
                    unguarded.add(name);
                }
            }
            return unguarded.isEmpty() ? Decision.ok() : Decision.violation(Set.copyOf(unguarded));
        } catch (Exception e) {
            // The inspector must NEVER throw. Fail-open with an observable counter so
            // pathological inputs surface in metrics rather than as request failures.
            parseFailureCounter.increment();
            if (log.isDebugEnabled()) {
                log.debug(
                        "Tenancy regex analysis failed ({}: {}): {}",
                        e.getClass().getSimpleName(),
                        e.getMessage(),
                        LoggingUtils.truncate(sql, 200));
            }
            return Decision.ok();
        }
    }

    /** Strip dialect quotes and the schema prefix from an identifier. */
    private static String unqualify(String raw) {
        if (raw == null) return "";
        String s = raw.trim();
        // Drop schema prefix first (it may be quoted too).
        int dot = s.lastIndexOf('.');
        if (dot >= 0) {
            s = s.substring(dot + 1).trim();
        }
        // Strip any stray dialect quote chars (", `, ') wherever they sit. Matched-pair stripping alone
        // leaves a malformed single-quote identifier (e.g. "practice) verbatim, so the lowercase lookup
        // would miss the scoped set and the table would escape enforcement. Removing every quote char
        // makes a malformed identifier degrade toward over-reporting (safe), not under-reporting.
        return s.replace("\"", "").replace("`", "").replace("'", "");
    }

    record Decision(boolean violated, Set<String> unguardedTables) {
        static Decision ok() {
            return new Decision(false, Set.of());
        }

        static Decision violation(Set<String> tables) {
            return new Decision(true, tables);
        }
    }
}
