// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import { exchangeNativeSignInResponseTransformer, getFeedbackResponseResponseTransformer, getInAppFeedbackResponseTransformer, getObservationResponseTransformer, getThreadResponseTransformer, listGroupsResponseTransformer, listPracticeGroupReviewRunsResponseTransformer, listPracticeGroupStandingsResponseTransformer, listPracticeStandingsResponseTransformer, listSessionsResponseTransformer, listThreadsResponseTransformer, listWorkspacesResponseTransformer, refreshNativeSessionResponseTransformer, replaceFeedbackResponseResponseTransformer } from './transformers.gen';
import type { CompleteFirstLoginConsentData, CompleteFirstLoginConsentResponses, DeleteCurrentUserData, DeleteCurrentUserResponses, DeleteFeedbackResponseData, DeleteFeedbackResponseErrors, DeleteFeedbackResponseResponses, DeleteThreadData, DeleteThreadErrors, DeleteThreadResponses, ExchangeNativeSignInData, ExchangeNativeSignInErrors, ExchangeNativeSignInResponses, GetConsentStatusData, GetConsentStatusResponses, GetCurrentUserData, GetCurrentUserResponses, GetFeedbackResponseData, GetFeedbackResponseErrors, GetFeedbackResponseResponses, GetInAppFeedbackData, GetInAppFeedbackResponses, GetNativeClientConfigurationData, GetNativeClientConfigurationResponses, GetObservationData, GetObservationErrors, GetObservationResponses, GetPushDeviceStatusData, GetPushDeviceStatusResponses, GetThreadData, GetThreadErrors, GetThreadResponses, ListGroupsData, ListGroupsResponses, ListIdentityProvidersData, ListIdentityProvidersResponses, ListPracticeGroupReviewRunsData, ListPracticeGroupReviewRunsErrors, ListPracticeGroupReviewRunsResponses, ListPracticeGroupStandingsData, ListPracticeGroupStandingsResponses, ListPracticeStandingsData, ListPracticeStandingsResponses, ListReviewedPracticesData, ListReviewedPracticesResponses, ListSessionsData, ListSessionsResponses, ListThreadsData, ListThreadsResponses, ListWorkspacesData, ListWorkspacesResponses, LogoutNativeSessionData, LogoutNativeSessionResponses, RefreshNativeSessionData, RefreshNativeSessionErrors, RefreshNativeSessionResponses, RegisterPushDeviceData, RegisterPushDeviceErrors, RegisterPushDeviceResponses, ReplaceFeedbackResponseData, ReplaceFeedbackResponseErrors, ReplaceFeedbackResponseResponses, RevokeOtherSessionsData, RevokeOtherSessionsResponses, RevokeSessionData, RevokeSessionResponses, SubmitInstanceProductFeedbackData, SubmitInstanceProductFeedbackResponses, UnregisterPushDeviceData, UnregisterPushDeviceResponses, UpdateResearchConsentData, UpdateResearchConsentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * What this server requires of the native app
 *
 * Public. An app that finds no such endpoint is talking to a server without native sign-in.
 */
export const getNativeClientConfiguration = <ThrowOnError extends boolean = false>(options?: Options<GetNativeClientConfigurationData, ThrowOnError>): RequestResult<GetNativeClientConfigurationResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetNativeClientConfigurationResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/auth/native/configuration',
  ...options
});

/**
 * End the native session its refresh secret belongs to
 */
export const logoutNativeSession = <ThrowOnError extends boolean = false>(options: Options<LogoutNativeSessionData, ThrowOnError>): RequestResult<LogoutNativeSessionResponses, unknown, ThrowOnError> => (options.client ?? client).post<LogoutNativeSessionResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/auth/native/logout',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Rotate the native session's access token and refresh secret
 */
export const refreshNativeSession = <ThrowOnError extends boolean = false>(options: Options<RefreshNativeSessionData, ThrowOnError>): RequestResult<RefreshNativeSessionResponses, RefreshNativeSessionErrors, ThrowOnError> => (options.client ?? client).post<RefreshNativeSessionResponses, RefreshNativeSessionErrors, ThrowOnError>({
  responseTransformer: refreshNativeSessionResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/auth/native/refresh',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Redeem a sign-in handoff code with its PKCE verifier
 */
export const exchangeNativeSignIn = <ThrowOnError extends boolean = false>(options: Options<ExchangeNativeSignInData, ThrowOnError>): RequestResult<ExchangeNativeSignInResponses, ExchangeNativeSignInErrors, ThrowOnError> => (options.client ?? client).post<ExchangeNativeSignInResponses, ExchangeNativeSignInErrors, ThrowOnError>({
  responseTransformer: exchangeNativeSignInResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/auth/native/token',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * List available identity providers
 */
export const listIdentityProviders = <ThrowOnError extends boolean = false>(options?: Options<ListIdentityProvidersData, ThrowOnError>): RequestResult<ListIdentityProvidersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListIdentityProvidersResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/identity-providers',
  ...options
});

/**
 * Send instance-scoped product feedback
 */
export const submitInstanceProductFeedback = <ThrowOnError extends boolean = false>(options: Options<SubmitInstanceProductFeedbackData, ThrowOnError>): RequestResult<SubmitInstanceProductFeedbackResponses, unknown, ThrowOnError> => (options.client ?? client).post<SubmitInstanceProductFeedbackResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/product-feedback',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Delete the current account (GDPR Art. 17)
 */
export const deleteCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<DeleteCurrentUserData, ThrowOnError>): RequestResult<DeleteCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<DeleteCurrentUserResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user',
  ...options
});

/**
 * Get the current user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user',
  ...options
});

/**
 * Get the current consent notice and status
 */
export const getConsentStatus = <ThrowOnError extends boolean = false>(options?: Options<GetConsentStatusData, ThrowOnError>): RequestResult<GetConsentStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetConsentStatusResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/consent',
  ...options
});

/**
 * Complete the first-login transparency step
 */
export const completeFirstLoginConsent = <ThrowOnError extends boolean = false>(options: Options<CompleteFirstLoginConsentData, ThrowOnError>): RequestResult<CompleteFirstLoginConsentResponses, unknown, ThrowOnError> => (options.client ?? client).put<CompleteFirstLoginConsentResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/consent',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Grant or withdraw research consent
 */
export const updateResearchConsent = <ThrowOnError extends boolean = false>(options: Options<UpdateResearchConsentData, ThrowOnError>): RequestResult<UpdateResearchConsentResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateResearchConsentResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/consent/research',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Stop push notifications on this installation
 */
export const unregisterPushDevice = <ThrowOnError extends boolean = false>(options: Options<UnregisterPushDeviceData, ThrowOnError>): RequestResult<UnregisterPushDeviceResponses, unknown, ThrowOnError> => (options.client ?? client).delete<UnregisterPushDeviceResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/push-devices/{installationId}',
  ...options
});

/**
 * Whether this server sends push notifications and this installation receives them
 */
export const getPushDeviceStatus = <ThrowOnError extends boolean = false>(options: Options<GetPushDeviceStatusData, ThrowOnError>): RequestResult<GetPushDeviceStatusResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPushDeviceStatusResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/push-devices/{installationId}',
  ...options
});

/**
 * Receive push notifications on this installation
 */
export const registerPushDevice = <ThrowOnError extends boolean = false>(options: Options<RegisterPushDeviceData, ThrowOnError>): RequestResult<RegisterPushDeviceResponses, RegisterPushDeviceErrors, ThrowOnError> => (options.client ?? client).put<RegisterPushDeviceResponses, RegisterPushDeviceErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/push-devices/{installationId}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Revoke all sessions except the current one
 */
export const revokeOtherSessions = <ThrowOnError extends boolean = false>(options?: Options<RevokeOtherSessionsData, ThrowOnError>): RequestResult<RevokeOtherSessionsResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<RevokeOtherSessionsResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/sessions',
  ...options
});

/**
 * List active sessions for the current user
 */
export const listSessions = <ThrowOnError extends boolean = false>(options?: Options<ListSessionsData, ThrowOnError>): RequestResult<ListSessionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSessionsResponses, unknown, ThrowOnError>({
  responseTransformer: listSessionsResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/sessions',
  ...options
});

/**
 * Revoke a single session
 */
export const revokeSession = <ThrowOnError extends boolean = false>(options: Options<RevokeSessionData, ThrowOnError>): RequestResult<RevokeSessionResponses, unknown, ThrowOnError> => (options.client ?? client).delete<RevokeSessionResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/user/sessions/{jti}',
  ...options
});

/**
 * List all workspaces
 */
export const listWorkspaces = <ThrowOnError extends boolean = false>(options?: Options<ListWorkspacesData, ThrowOnError>): RequestResult<ListWorkspacesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListWorkspacesResponses, unknown, ThrowOnError>({
  responseTransformer: listWorkspacesResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces',
  ...options
});

/**
 * List the current user's mentor threads in this workspace
 */
export const listThreads = <ThrowOnError extends boolean = false>(options: Options<ListThreadsData, ThrowOnError>): RequestResult<ListThreadsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListThreadsResponses, unknown, ThrowOnError>({
  responseTransformer: listThreadsResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/mentor/threads',
  ...options
});

/**
 * Delete a mentor thread (cascades to messages, votes, parts)
 */
export const deleteThread = <ThrowOnError extends boolean = false>(options: Options<DeleteThreadData, ThrowOnError>): RequestResult<DeleteThreadResponses, DeleteThreadErrors, ThrowOnError> => (options.client ?? client).delete<DeleteThreadResponses, DeleteThreadErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/mentor/threads/{threadId}',
  ...options
});

/**
 * Get a mentor thread with its full message history
 */
export const getThread = <ThrowOnError extends boolean = false>(options: Options<GetThreadData, ThrowOnError>): RequestResult<GetThreadResponses, GetThreadErrors, ThrowOnError> => (options.client ?? client).get<GetThreadResponses, GetThreadErrors, ThrowOnError>({
  responseTransformer: getThreadResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/mentor/threads/{threadId}',
  ...options
});

/**
 * List practice groups
 *
 * Returns the workspace's practice groups
 */
export const listGroups = <ThrowOnError extends boolean = false>(options: Options<ListGroupsData, ThrowOnError>): RequestResult<ListGroupsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListGroupsResponses, unknown, ThrowOnError>({
  responseTransformer: listGroupsResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practice-groups',
  ...options
});

/**
 * List the current developer's practice group standings
 *
 * Returns every active practice group's standing, direction, guidance, and supporting observations.
 */
export const listPracticeGroupStandings = <ThrowOnError extends boolean = false>(options: Options<ListPracticeGroupStandingsData, ThrowOnError>): RequestResult<ListPracticeGroupStandingsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListPracticeGroupStandingsResponses, unknown, ThrowOnError>({
  responseTransformer: listPracticeGroupStandingsResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practice-groups/standings',
  ...options
});

/**
 * List complete review runs for a practice group
 *
 * Returns complete review runs newest first, including visible undecided observations.
 */
export const listPracticeGroupReviewRuns = <ThrowOnError extends boolean = false>(options: Options<ListPracticeGroupReviewRunsData, ThrowOnError>): RequestResult<ListPracticeGroupReviewRunsResponses, ListPracticeGroupReviewRunsErrors, ThrowOnError> => (options.client ?? client).get<ListPracticeGroupReviewRunsResponses, ListPracticeGroupReviewRunsErrors, ThrowOnError>({
  responseTransformer: listPracticeGroupReviewRunsResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practice-groups/{groupSlug}/review-runs',
  ...options
});

/**
 * The current developer's in-app feedback
 *
 * Process-level messages prepared for the authenticated developer: for each habit that recurs in their work, what the pattern is, the pieces of work it was observed on, and one thing to try next. Distinct from in-context notes (which say what is wrong in one diff) and from the mentor conversation (which asks rather than tells). Reading a message is what delivers it, so this GET records the delivery.
 */
export const getInAppFeedback = <ThrowOnError extends boolean = false>(options: Options<GetInAppFeedbackData, ThrowOnError>): RequestResult<GetInAppFeedbackResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetInAppFeedbackResponses, unknown, ThrowOnError>({
  responseTransformer: getInAppFeedbackResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/feedback/in-app',
  ...options
});

/**
 * Delete the response to delivered feedback
 */
export const deleteFeedbackResponse = <ThrowOnError extends boolean = false>(options: Options<DeleteFeedbackResponseData, ThrowOnError>): RequestResult<DeleteFeedbackResponseResponses, DeleteFeedbackResponseErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFeedbackResponseResponses, DeleteFeedbackResponseErrors, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/feedback/{feedbackId}/response',
  ...options
});

/**
 * Get the current feedback response
 */
export const getFeedbackResponse = <ThrowOnError extends boolean = false>(options: Options<GetFeedbackResponseData, ThrowOnError>): RequestResult<GetFeedbackResponseResponses, GetFeedbackResponseErrors, ThrowOnError> => (options.client ?? client).get<GetFeedbackResponseResponses, GetFeedbackResponseErrors, ThrowOnError>({
  responseTransformer: getFeedbackResponseResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/feedback/{feedbackId}/response',
  ...options
});

/**
 * Replace the response to delivered feedback
 *
 * Sets the complete current response. Repeating the same request has no effect.
 */
export const replaceFeedbackResponse = <ThrowOnError extends boolean = false>(options: Options<ReplaceFeedbackResponseData, ThrowOnError>): RequestResult<ReplaceFeedbackResponseResponses, ReplaceFeedbackResponseErrors, ThrowOnError> => (options.client ?? client).put<ReplaceFeedbackResponseResponses, ReplaceFeedbackResponseErrors, ThrowOnError>({
  responseTransformer: replaceFeedbackResponseResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/feedback/{feedbackId}/response',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Get observation detail
 */
export const getObservation = <ThrowOnError extends boolean = false>(options: Options<GetObservationData, ThrowOnError>): RequestResult<GetObservationResponses, GetObservationErrors, ThrowOnError> => (options.client ?? client).get<GetObservationResponses, GetObservationErrors, ThrowOnError>({
  responseTransformer: getObservationResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/observations/{observationId}',
  ...options
});

/**
 * List reviewed practices, developer-facing
 *
 * Returns the developer-facing name, group, rationale, and example for every practice the workspace reviews (any autonomy above OFF)
 */
export const listReviewedPractices = <ThrowOnError extends boolean = false>(options: Options<ListReviewedPracticesData, ThrowOnError>): RequestResult<ListReviewedPracticesResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListReviewedPracticesResponses, unknown, ThrowOnError>({
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/reviewed',
  ...options
});

/**
 * List the current developer's practice standings
 *
 * Returns each practice's standing, direction, supporting observations, and developer guidance.
 */
export const listPracticeStandings = <ThrowOnError extends boolean = false>(options: Options<ListPracticeStandingsData, ThrowOnError>): RequestResult<ListPracticeStandingsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListPracticeStandingsResponses, unknown, ThrowOnError>({
  responseTransformer: listPracticeStandingsResponseTransformer,
  security: [{ scheme: 'bearer', type: 'http' }],
  url: '/workspaces/{workspaceSlug}/practices/standings',
  ...options
});
