// This file is auto-generated by @hey-api/openapi-ts

import type { ExchangeNativeSignInResponse, GetFeedbackResponseResponse, GetInAppFeedbackResponse, GetObservationResponse, GetThreadResponse, ListGroupsResponse, ListPracticeGroupReviewRunsResponse, ListPracticeGroupStandingsResponse, ListPracticeStandingsResponse, ListSessionsResponse, ListThreadsResponse, ListWorkspacesResponse, RefreshNativeSessionResponse, ReplaceFeedbackResponseResponse } from './types.gen';

const nativeSessionTokensSchemaResponseTransformer = (data: any) => {
  data.accessTokenExpiresAt = new Date(data.accessTokenExpiresAt);
  data.sessionExpiresAt = new Date(data.sessionExpiresAt);
  return data;
};

export const refreshNativeSessionResponseTransformer = async (data: any): Promise<RefreshNativeSessionResponse> => {
  data = nativeSessionTokensSchemaResponseTransformer(data);
  return data;
};

export const exchangeNativeSignInResponseTransformer = async (data: any): Promise<ExchangeNativeSignInResponse> => {
  data = nativeSessionTokensSchemaResponseTransformer(data);
  return data;
};

const sessionViewSchemaResponseTransformer = (data: any) => {
  if (data.expiresAt) {
    data.expiresAt = new Date(data.expiresAt);
  }
  if (data.issuedAt) {
    data.issuedAt = new Date(data.issuedAt);
  }
  return data;
};

export const listSessionsResponseTransformer = async (data: any): Promise<ListSessionsResponse> => {
  data = data.map((item: any) => sessionViewSchemaResponseTransformer(item));
  return data;
};

const workspaceListItemSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  return data;
};

export const listWorkspacesResponseTransformer = async (data: any): Promise<ListWorkspacesResponse> => {
  data = data.map((item: any) => workspaceListItemSchemaResponseTransformer(item));
  return data;
};

const chatThreadSummarySchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const listThreadsResponseTransformer = async (data: any): Promise<ListThreadsResponse> => {
  data = data.map((item: any) => chatThreadSummarySchemaResponseTransformer(item));
  return data;
};

const chatMessageSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

const chatThreadDetailSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.messages) {
    data.messages = data.messages.map((item: any) => chatMessageSchemaResponseTransformer(item));
  }
  return data;
};

export const getThreadResponseTransformer = async (data: any): Promise<GetThreadResponse> => {
  data = chatThreadDetailSchemaResponseTransformer(data);
  return data;
};

const practiceGroupSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  return data;
};

export const listGroupsResponseTransformer = async (data: any): Promise<ListGroupsResponse> => {
  data = data.map((item: any) => practiceGroupSchemaResponseTransformer(item));
  return data;
};

const trendSupportSchemaResponseTransformer = (data: any) => {
  if (data.firstOpportunityAt) {
    data.firstOpportunityAt = new Date(data.firstOpportunityAt);
  }
  if (data.lastOpportunityAt) {
    data.lastOpportunityAt = new Date(data.lastOpportunityAt);
  }
  return data;
};

const practiceGroupStandingSchemaResponseTransformer = (data: any) => {
  if (data.feedbackSince) {
    data.feedbackSince = new Date(data.feedbackSince);
  }
  if (data.trendSupport) {
    data.trendSupport = trendSupportSchemaResponseTransformer(data.trendSupport);
  }
  return data;
};

export const listPracticeGroupStandingsResponseTransformer = async (data: any): Promise<ListPracticeGroupStandingsResponse> => {
  data = data.map((item: any) => practiceGroupStandingSchemaResponseTransformer(item));
  return data;
};

const feedbackResponseSchemaResponseTransformer = (data: any) => {
  if (data.respondedAt) {
    data.respondedAt = new Date(data.respondedAt);
  }
  return data;
};

const observationDetailSchemaResponseTransformer = (data: any) => {
  if (data.feedbackResponse) {
    data.feedbackResponse = feedbackResponseSchemaResponseTransformer(data.feedbackResponse);
  }
  data.observedAt = new Date(data.observedAt);
  return data;
};

const practiceGroupReviewRunSchemaResponseTransformer = (data: any) => {
  data.observations = data.observations.map((item: any) => observationDetailSchemaResponseTransformer(item));
  data.reviewedAt = new Date(data.reviewedAt);
  return data;
};

const practiceGroupReviewRunsPageSchemaResponseTransformer = (data: any) => {
  data.content = data.content.map((item: any) => practiceGroupReviewRunSchemaResponseTransformer(item));
  return data;
};

export const listPracticeGroupReviewRunsResponseTransformer = async (data: any): Promise<ListPracticeGroupReviewRunsResponse> => {
  data = practiceGroupReviewRunsPageSchemaResponseTransformer(data);
  return data;
};

const inAppCleanWorkSchemaResponseTransformer = (data: any) => {
  data.reviewedAt = new Date(data.reviewedAt);
  return data;
};

const inAppEvidenceSchemaResponseTransformer = (data: any) => {
  data.observedAt = new Date(data.observedAt);
  return data;
};

const inAppFeedbackSchemaResponseTransformer = (data: any) => {
  data.cleanWork = data.cleanWork.map((item: any) => inAppCleanWorkSchemaResponseTransformer(item));
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt);
  }
  data.evidence = data.evidence.map((item: any) => inAppEvidenceSchemaResponseTransformer(item));
  data.preparedAt = new Date(data.preparedAt);
  if (data.readAt) {
    data.readAt = new Date(data.readAt);
  }
  if (data.response) {
    data.response = feedbackResponseSchemaResponseTransformer(data.response);
  }
  return data;
};

export const getInAppFeedbackResponseTransformer = async (data: any): Promise<GetInAppFeedbackResponse> => {
  data = data.map((item: any) => inAppFeedbackSchemaResponseTransformer(item));
  return data;
};

export const getFeedbackResponseResponseTransformer = async (data: any): Promise<GetFeedbackResponseResponse> => {
  if (data) {
    data = feedbackResponseSchemaResponseTransformer(data);
  }
  return data;
};

export const replaceFeedbackResponseResponseTransformer = async (data: any): Promise<ReplaceFeedbackResponseResponse> => {
  data = feedbackResponseSchemaResponseTransformer(data);
  return data;
};

export const getObservationResponseTransformer = async (data: any): Promise<GetObservationResponse> => {
  data = observationDetailSchemaResponseTransformer(data);
  return data;
};

const practiceStandingSchemaResponseTransformer = (data: any) => {
  if (data.trendSupport) {
    data.trendSupport = trendSupportSchemaResponseTransformer(data.trendSupport);
  }
  return data;
};

export const listPracticeStandingsResponseTransformer = async (data: any): Promise<ListPracticeStandingsResponse> => {
  data = data.map((item: any) => practiceStandingSchemaResponseTransformer(item));
  return data;
};
