// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * The autonomy in force here, whether it was set here or inherited, and the level that decided it
 */
export type AutonomyAssignment = {
  /**
   * The autonomy actually in force
   */
  effective: 'OFF' | 'HUMAN_APPROVAL' | 'AUTOMATIC';
  /**
   * Whether autonomy is inherited
   */
  inherited: boolean;
  /**
   * The local override, or null when autonomy is inherited
   */
  override?: 'OFF' | 'HUMAN_APPROVAL' | 'AUTOMATIC';
  /**
   * Which level decided the effective autonomy
   */
  source: 'PRACTICE' | 'GROUP' | 'WORKSPACE';
};

/**
 * The catalog entry a workspace copy came from and whether it differs now
 */
export type CatalogOrigin = {
  link: 'IN_SYNC' | 'LOCALLY_EDITED' | 'UPDATE_AVAILABLE' | 'DECLINED';
  /**
   * Slug of the catalog entry this copy was made from
   */
  slug: string;
  /**
   * Whether new workspaces receive the source entry
   */
  sourceOffered: boolean;
};

/**
 * Mentor chat message in AI SDK UIMessage shape.
 */
export type ChatMessage = {
  createdAt?: Date;
  id?: string;
  /**
   * Per-turn metadata: status, model, costUsd, usage, …
   */
  metadata?: {
    [key: string]: unknown;
  };
  parentMessageId?: string;
  parts?: Array<unknown>;
  role?: string;
};

/**
 * Mentor chat thread with all messages and the owner's votes on them.
 */
export type ChatThreadDetail = {
  createdAt?: Date;
  id?: string;
  messages?: Array<ChatMessage>;
  title?: string;
  votes?: {
    [key: string]: boolean;
  };
};

/**
 * Mentor chat thread summary (no messages).
 */
export type ChatThreadSummary = {
  createdAt?: Date;
  id?: string;
  title?: string;
};

export type ConsentStatus = {
  completed: boolean;
  /**
   * Version of the first-login wording the client must be rendering
   */
  noticeVersion: string;
  participateInResearch: boolean;
  /**
   * Organisation running the optional research programme, or null when this instance runs none
   */
  researchOrganization?: string;
};

export type CurrentUserView = {
  accessTokenExpiresAt?: number;
  appRole?: string;
  avatarUrl?: string;
  displayName?: string;
  gitProviderId?: string;
  id?: number;
  identityProvider?: string;
  linkedProviders?: Array<LinkedProvider>;
  primaryEmail?: string;
  profileUrl?: string;
  roles?: Array<string>;
  status?: string;
  username?: string;
};

/**
 * A verified quote and its exact source location
 */
export type EvidenceCitation = {
  artifactPath: string;
  endLine: number;
  path: string;
  quote?: string;
  quoteRedacted: boolean;
  revision?: string;
  side?: 'OLD' | 'NEW';
  sourceKind: string;
  startLine: number;
};

/**
 * Why this practice had nothing to judge in this work
 */
export type EvidenceInapplicability = {
  /**
   * The sources the review read to conclude this, by source kind
   */
  consulted: Array<string>;
  /**
   * The fact about this work that means there was nothing to look at
   */
  ruledOutBy: string;
  /**
   * What this practice looks for
   */
  subject: string;
};

/**
 * Where the review looked when it found nothing
 */
export type EvidenceSearch = {
  /**
   * How far the search reached — the work this absence holds over
   */
  boundary: string;
  /**
   * The sources the review searched, by source kind
   */
  consulted: Array<string>;
  /**
   * What the review looked for in this work
   */
  lookedFor: string;
};

/**
 * What the review could not settle, and what would settle it
 */
export type EvidenceUndecidability = {
  /**
   * The question this work left open
   */
  openQuestion: string;
  /**
   * What would have answered it
   */
  wouldSettleIt: string;
};

export type FeedbackRequest = {
  kind: 'IDEA' | 'BUG' | 'FEEDBACK';
  message: string;
  pagePath?: string;
  userAgent?: string;
};

/**
 * The recipient's current assessment and resolution of delivered feedback
 */
export type FeedbackResponse = {
  comment?: string;
  feedbackId: string;
  resolution?: 'ADDRESSED' | 'DISPUTED' | 'NOT_APPLICABLE';
  respondedAt?: Date;
  usefulness?: 'HELPFUL' | 'UNHELPFUL';
};

/**
 * The complete response to delivered feedback
 */
export type FeedbackResponseRequest = {
  /**
   * Optional explanation; required when resolution is DISPUTED.
   */
  comment?: string;
  /**
   * What the recipient decided to do with the feedback
   */
  resolution?: 'ADDRESSED' | 'DISPUTED' | 'NOT_APPLICABLE';
  /**
   * How useful the feedback was
   */
  usefulness?: 'HELPFUL' | 'UNHELPFUL';
};

/**
 * Distinct work artifacts of one kind that contributed feedback
 */
export type FeedbackSourceCount = {
  /**
   * Distinct artifacts of this kind in the selected time period
   */
  count: number;
  /**
   * The kind of work the feedback came from
   */
  workKind: string;
};

export type FirstLoginConsent = {
  noticeVersion: string;
  /**
   * Required when the instance names a research organisation, omitted otherwise
   */
  participateInResearch?: boolean;
  /**
   * The organisation the research question named on screen; omitted when it asked none
   */
  researchOrganization?: string;
  termsAccepted: boolean;
};

/**
 * One row per sign-in option. <code>providerType</code> drives the SPA's icon choice; <code>baseUrl</code> is
 *  the OAuth instance origin (scheme + host[:port]) of the authorization endpoint, so the
 *  workspace-creation wizard can match a target instance to its login.
 *
 *  <p><b>baseUrl is the OAuth origin, not the SCM API origin.</b> It is only meaningful for GitLab rows,
 *  where the OAuth origin and the API origin coincide (e.g. <code>https://gitlab.example.com</code>). For a
 *  GitHub row it is <code>https://github.com</code> (the OAuth host), NOT <code>https://api.github.com</code>; the
 *  sole consumer (the workspace wizard) matches GitLab self-hosted origins and never relies on the GitHub
 *  value, so the discrepancy is harmless. Do not treat this as an SCM API base URL.
 */
export type IdentityProviderView = {
  baseUrl?: string;
  displayName?: string;
  providerType?: string;
  registrationId?: string;
};

/**
 * One piece of work that came back clean on the practice since the feedback was prepared
 */
export type InAppCleanWork = {
  /**
   * When that piece was reviewed
   */
  reviewedAt: Date;
  /**
   * The piece of work, as every surface names it
   */
  reviewedWork: ReviewedWorkRef;
};

/**
 * One piece of work the pattern was observed on
 */
export type InAppEvidence = {
  /**
   * When the measurement behind this occurrence was taken
   */
  observedAt: Date;
  /**
   * What the review made of this piece of work: a behaviour demonstrated, a trap avoided, something harmful done, or something needed left out
   */
  outcome: 'DEMONSTRATED_STRENGTH' | 'SAFE_AVOIDANCE' | 'COMMISSION_PROBLEM' | 'OMISSION_GAP' | 'NOT_APPLICABLE' | 'UNDETERMINED';
  /**
   * The piece of work, as every surface names it
   */
  reviewedWork: ReviewedWorkRef;
  /**
   * What the review recorded on this piece of work
   */
  summary?: string;
};

/**
 * A process-level message on the developer's own practice pages
 */
export type InAppFeedback = {
  /**
   * The message, as Markdown, without the headline and the next step
   */
  body: string;
  /**
   * Clean pieces of work in a row on the practice that resolve this feedback
   */
  cleanNeeded: number;
  /**
   * The pieces of work in a row that came back clean on the practice since the feedback was prepared, each with the date it was reviewed, oldest first, at most cleanNeeded of them; a problem empties it, and once resolved these are exactly the pieces that resolved it
   */
  cleanWork: Array<InAppCleanWork>;
  /**
   * When it stopped being open: the earliest of the work completing its clean run, the developer answering that it is addressed or not applicable, and the practice changing its review rules after it was prepared; null while it is open
   */
  closedAt?: Date;
  /**
   * What closed it, for the moment closedAt names; on a tie the work, then the developer, then the practice; null while it is open
   */
  closedBy?: 'WORK' | 'DEVELOPER' | 'PRACTICE_CHANGED';
  /**
   * The pieces of work the habit was observed on, newest first
   */
  evidence: Array<InAppEvidence>;
  /**
   * Group display name; null when the practice has none
   */
  groupName?: string;
  /**
   * Group the practice sits in; null when the practice has none
   */
  groupSlug?: string;
  /**
   * Short headline naming the habit, never the person
   */
  headline: string;
  id: string;
  /**
   * The habit to try next, on its own; null for feedback prepared without one
   */
  nextStep?: string;
  practiceName: string;
  /**
   * Practice this habit belongs to
   */
  practiceSlug: string;
  /**
   * When the message was composed
   */
  preparedAt: Date;
  /**
   * When this developer first opened it; null until they have
   */
  readAt?: Date;
  /**
   * The developer's current response to this feedback; null while they have none
   */
  response?: FeedbackResponse;
  /**
   * What good looks like, in the developer's framing
   */
  whatGoodLooksLike?: string;
  /**
   * Why this practice matters, in the developer's framing
   */
  whyItMatters?: string;
};

/**
 * A provider instance the current user is linked to: its type + server-url origin.
 */
export type LinkedProvider = {
  serverUrl?: string;
  type?: string;
};

export type NativeClientConfiguration = {
  minimumAppVersion: string;
  /**
   * Web application address for privacy, account export and browser-only workflows
   */
  webappUrl: string;
};

export type NativeRefreshRequest = {
  refreshToken: string;
};

export type NativeSessionTokens = {
  accessToken: string;
  accessTokenExpiresAt: Date;
  nativeSessionId: string;
  refreshToken: string;
  sessionExpiresAt: Date;
};

export type NativeTokenRequest = {
  code: string;
  codeVerifier: string;
};

/**
 * Full practice observation detail including delivered feedback and evidence
 */
export type ObservationDetail = {
  /**
   * Artifact entity ID
   */
  artifactId: number;
  /**
   * Artifact type (e.g. PULL_REQUEST)
   */
  artifactKind: string;
  /**
   * Link to the reviewed artifact on its platform (null when it cannot be resolved)
   */
  artifactUrl?: string;
  /**
   * Contextual desirability of the specified behavior: GOOD or BAD; null unless assessmentStatus is ASSESSED
   */
  assessment?: 'GOOD' | 'BAD';
  assessmentStatus: 'ASSESSED' | 'NOT_APPLICABLE' | 'UNDETERMINED';
  /**
   * Whether an observation still has current review rules and supporting work snapshot
   */
  claimCurrentness: 'CURRENT' | 'STALE' | 'UNVERIFIABLE';
  /**
   * What to do — the text of the newest feedback that said something about this observation to this developer (null if nothing was said)
   */
  deliveredFeedback?: string;
  evidence?: ObservationEvidence;
  /**
   * Evidence-based rationale for the observation
   */
  evidenceRationale?: string;
  /**
   * The developer's standing answer to the very feedback whose text deliveredFeedback shows, with that feedback's id as the handle for responding (null when nothing was said, or when the feedback that said it failed to deliver and so cannot be answered)
   */
  feedbackResponse?: FeedbackResponse;
  /**
   * Observation ID
   */
  id: string;
  /**
   * The next step the review wrote about this observation, whether or not the feedback carrying it was delivered (null when it wrote none)
   */
  nextStep?: string;
  /**
   * When the observation was made
   */
  observedAt: Date;
  /**
   * What occasioned the measurement; never mix origins in one trend line
   */
  origin: 'LIVE' | 'MANUAL' | 'BACKFILL';
  /**
   * Derived from presence and contextual behavior assessment; null unless assessed
   */
  readonly outcome?: 'POSITIVE' | 'NEGATIVE';
  /**
   * Practice name
   */
  practiceName: string;
  /**
   * Practice slug
   */
  practiceSlug: string;
  /**
   * PRESENT or ABSENT only when ASSESSED
   */
  presence?: 'PRESENT' | 'ABSENT';
  /**
   * Cross-run locus key; null when continuity is unavailable
   */
  recurrenceKey?: string;
  /**
   * Severity level (null unless outcome is NEGATIVE)
   */
  severity?: 'CRITICAL' | 'MAJOR' | 'MINOR' | 'INFO';
  /**
   * Observation summary
   */
  summary: string;
};

/**
 * Verified, source-bound evidence for an observation
 */
export type ObservationEvidence = {
  citations: Array<EvidenceCitation>;
  detector?: string;
  /**
   * Why this practice had nothing to judge here; null unless the review recorded a reason
   */
  inapplicability?: EvidenceInapplicability;
  /**
   * Where the review looked when it found nothing; null unless it recorded a search
   */
  search?: EvidenceSearch;
  /**
   * What the review could not settle; null unless it recorded an open question
   */
  undecidability?: EvidenceUndecidability;
};

/**
 * A practice group grouping related practices into a learning objective
 */
export type PracticeGroup = {
  /**
   * How much autonomy the system has over every practice in this group that holds no autonomy of its own, whether that was set here or inherited from the workspace, and which level decided it
   */
  autonomy: AutonomyAssignment;
  catalogOrigin?: CatalogOrigin;
  /**
   * Optional palette colour key for the group's chip
   */
  color?: string;
  /**
   * Timestamp when the group was created
   */
  createdAt: Date;
  /**
   * What this group develops
   */
  description?: string;
  /**
   * Sort order within the workspace
   */
  displayOrder: number;
  /**
   * Optional lucide icon name for the group's chip
   */
  icon?: string;
  /**
   * Group ID
   */
  id: number;
  /**
   * Human-readable name
   */
  name: string;
  /**
   * URL-safe identifier unique within the workspace
   */
  slug: string;
  /**
   * Timestamp when the group was last updated
   */
  updatedAt?: Date;
  /**
   * Whether this group is shown in practice dashboards
   */
  visibleInPracticeDashboards: boolean;
};

/**
 * A complete review run in a developer's practice-group history
 */
export type PracticeGroupReviewRun = {
  /**
   * Every visible observation of the run, complete enough to open in place
   */
  observations: Array<ObservationDetail>;
  reviewId: string;
  reviewedAt: Date;
  reviewedWork: ReviewedWorkRef;
};

/**
 * A page of visible review runs
 */
export type PracticeGroupReviewRunsPage = {
  content: Array<PracticeGroupReviewRun>;
  hasNext?: boolean;
  page?: number;
  size?: number;
};

/**
 * A developer's derived qualitative standing for one Group including 1<=n<many practices
 */
export type PracticeGroupStanding = {
  /**
   * Evidence-weighted, opportunity-indexed direction across the group's practices
   */
  direction?: 'IMPROVING' | 'DECLINING' | 'UNCERTAIN' | 'INSUFFICIENT_EVIDENCE';
  /**
   * Oldest contributing observation, for provenance only (null without a verdict)
   */
  feedbackSince?: Date;
  /**
   * Calendar span covered by the feedback, for provenance only; never a trend-analysis unit
   */
  feedbackSpanDays?: number;
  /**
   * Group name
   */
  groupName: string;
  /**
   * Group slug
   */
  groupSlug: string;
  /**
   * Developer guidance aggregated from the group's feedback (null unless the standing is a verdict). The deterministic summary combines standing, next focus, and developer-facing catalog guidance.
   */
  guidance?: string;
  /**
   * How the guidance text was produced (null when there is no guidance)
   */
  guidanceSource?: 'RULE_BASED';
  /**
   * Supporting observations the standing derives from (problems first); empty without a verdict
   */
  observations: Array<PracticeStandingObservation>;
  /**
   * Distinct pieces of reviewed work the observations come from, per kind (provenance, not a score); empty without a verdict
   */
  sources: Array<FeedbackSourceCount>;
  /**
   * Derived qualitative standing across the group's practices
   */
  standing: 'DEVELOPING' | 'STRENGTH' | 'MIXED' | 'NOT_OBSERVED' | 'NO_OPPORTUNITY';
  /**
   * Evidence support and provenance for the direction
   */
  trendSupport?: TrendSupport;
};

/**
 * A developer's readable feedback for one practice
 */
export type PracticeStanding = {
  /**
   * Opportunity-indexed direction of this practice's recent evidence
   */
  direction?: 'IMPROVING' | 'DECLINING' | 'UNCERTAIN' | 'INSUFFICIENT_EVIDENCE';
  /**
   * Group name this practice belongs to, if any
   */
  groupName?: string;
  /**
   * Group slug this practice belongs to, if any
   */
  groupSlug?: string;
  /**
   * Practice name
   */
  name: string;
  /**
   * Practice slug
   */
  slug: string;
  /**
   * Where the developer stands on this practice, or why no standing could be formed
   */
  standing: 'DEVELOPING' | 'STRENGTH' | 'MIXED' | 'NOT_OBSERVED' | 'NO_OPPORTUNITY';
  /**
   * What the developer already does well here
   */
  strengths: Array<PracticeStandingObservation>;
  /**
   * Specific feedback to act on (highest-impact first)
   */
  toWorkOn: Array<PracticeStandingObservation>;
  /**
   * Evidence support and provenance for the direction
   */
  trendSupport?: TrendSupport;
  /**
   * A concrete picture of doing this well
   */
  whatGoodLooksLike?: string;
  /**
   * Why this practice matters, in plain language
   */
  whyItMatters?: string;
};

/**
 * A single piece of practice feedback to read and act on
 */
export type PracticeStandingObservation = {
  /**
   * What to do — the text of the newest feedback that said something about this observation to this developer (null if nothing was said)
   */
  deliveredFeedback?: string;
  /**
   * What this observation says about the developer: a behaviour demonstrated, a trap avoided, something harmful done, or something needed left out. The lists only separate positive from negative, so this is what tells the two kinds of each apart. Only assessed observations reach a standing, so NOT_APPLICABLE and UNDETERMINED never appear here.
   */
  kind: 'DEMONSTRATED_STRENGTH' | 'SAFE_AVOIDANCE' | 'COMMISSION_PROBLEM' | 'OMISSION_GAP' | 'NOT_APPLICABLE' | 'UNDETERMINED';
  /**
   * Where in the work, e.g. "FrameRecorder.swift:212", when known
   */
  locator?: string;
  /**
   * Observation id — handle to open the full detail
   */
  observationId: string;
  /**
   * Why this observation was recorded. BACKFILL means it came from a review of past work rather than from something that just happened, and nothing was posted anywhere at the time.
   */
  origin: 'LIVE' | 'MANUAL' | 'BACKFILL';
  /**
   * Positive or negative consequence of this assessed observation
   */
  readonly outcome?: 'POSITIVE' | 'NEGATIVE';
  /**
   * Identifier of the reviewed work
   */
  reviewedWorkId: number;
  /**
   * Impact level (null unless assessed BAD)
   */
  severity?: 'CRITICAL' | 'MAJOR' | 'MINOR' | 'INFO';
  /**
   * The headline of the feedback
   */
  title: string;
  /**
   * The kind of reviewed work this is about
   */
  workKind: string;
};

export type ProblemDetail = {
  detail?: string;
  instance?: string;
  properties?: {
    [key: string]: unknown;
  };
  status?: number;
  title?: string;
  type?: string;
};

export type PushDeviceRegistration = {
  expoPushToken: string;
  platform: 'IOS' | 'ANDROID';
};

export type PushDeviceStatus = {
  available: boolean;
  registered: boolean;
};

export type ResearchConsent = {
  granted: boolean;
  noticeVersion: string;
  /**
   * The organisation this control named on screen
   */
  researchOrganization?: string;
};

/**
 * Developer-facing view of a practice — criteria absent by construction
 */
export type ReviewedPractice = {
  /**
   * Slug of the practice group this belongs to, if any
   */
  groupSlug?: string;
  /**
   * Human-readable name
   */
  name: string;
  /**
   * URL-safe identifier
   */
  slug: string;
  /**
   * A concrete picture of doing this well
   */
  whatGoodLooksLike?: string;
  /**
   * Why this practice matters, in plain language
   */
  whyItMatters?: string;
};

/**
 * A piece of reviewed work as every surface names it: enough to print a link
 */
export type ReviewedWorkRef = {
  /**
   * Identifier of the work within its kind
   */
  id: string;
  /**
   * Artifact kind id
   */
  kind: string;
  /**
   * Short label the page prints: "#22", "!425", "#backend-review" or a document title
   */
  label: string;
  /**
   * The provider the work lives at, which decides its noun: a GitLab scm.pull_request is a merge request; absent when the run that named the work is gone
   */
  provider?: 'GITHUB' | 'GITLAB' | 'SLACK' | 'OUTLINE';
  /**
   * Repository the work belongs to, for pull requests and issues
   */
  repositoryName?: string;
  /**
   * The work's own title: a pull request's, an issue's or a document's; a conversation thread has none
   */
  title?: string;
  /**
   * The work's page at its provider, when the provider exposes one
   */
  url?: string;
};

export type SessionView = {
  current?: boolean;
  expiresAt?: Date;
  ip?: string;
  issuedAt?: Date;
  jti?: string;
  /**
   * The native app, whose session outlives this token until expiresAt
   */
  nativeApp: boolean;
  userAgent?: string;
};

export type TrendSupport = {
  bundleSize: number;
  calendarSpanDays?: number;
  comparablePractices?: number;
  credibilityThreshold: number;
  currentOpportunities: number;
  eligiblePractices?: number;
  firstOpportunityAt?: Date;
  lastOpportunityAt?: Date;
  /**
   * Distinct pieces of reviewed work the trend rests on, across both bundles
   */
  opportunities: number;
  opportunitiesUntilComparable: number;
  previousOpportunities: number;
  ropeHalfWidth: number;
};

/**
 * Summary information about a workspace for list views
 */
export type WorkspaceListItem = {
  /**
   * Git provider account login associated with this workspace
   */
  accountLogin: string;
  /**
   * Timestamp when the workspace was created
   */
  createdAt: Date;
  /**
   * Human-readable name of the workspace
   */
  displayName: string;
  /**
   * Unique identifier of the workspace
   */
  id: number;
  /**
   * Whether the leaderboard is enabled
   */
  leaderboardEnabled: boolean;
  /**
   * Whether league tiers and rankings are enabled
   */
  leaguesEnabled: boolean;
  /**
   * Whether the Pi mentor chat feature is enabled
   */
  mentorEnabled: boolean;
  /**
   * Whether the practice review feature is enabled
   */
  practicesEnabled: boolean;
  /**
   * Whether the league/progression system is enabled
   */
  progressionEnabled: boolean;
  /**
   * High-level git provider type (GITHUB or GITLAB), or null if no SCM connection bound
   */
  providerType?: 'GITHUB' | 'GITLAB' | 'SLACK' | 'OUTLINE';
  /**
   * Current lifecycle status of the workspace (PENDING, ACTIVE, ARCHIVED)
   */
  status: string;
  /**
   * URL-friendly identifier for the workspace
   */
  workspaceSlug: string;
};

/**
 * Full practice observation detail including delivered feedback and evidence
 */
export type ObservationDetailWritable = {
  /**
   * Artifact entity ID
   */
  artifactId: number;
  /**
   * Artifact type (e.g. PULL_REQUEST)
   */
  artifactKind: string;
  /**
   * Link to the reviewed artifact on its platform (null when it cannot be resolved)
   */
  artifactUrl?: string;
  /**
   * Contextual desirability of the specified behavior: GOOD or BAD; null unless assessmentStatus is ASSESSED
   */
  assessment?: 'GOOD' | 'BAD';
  assessmentStatus: 'ASSESSED' | 'NOT_APPLICABLE' | 'UNDETERMINED';
  /**
   * Whether an observation still has current review rules and supporting work snapshot
   */
  claimCurrentness: 'CURRENT' | 'STALE' | 'UNVERIFIABLE';
  /**
   * What to do — the text of the newest feedback that said something about this observation to this developer (null if nothing was said)
   */
  deliveredFeedback?: string;
  evidence?: ObservationEvidence;
  /**
   * Evidence-based rationale for the observation
   */
  evidenceRationale?: string;
  /**
   * The developer's standing answer to the very feedback whose text deliveredFeedback shows, with that feedback's id as the handle for responding (null when nothing was said, or when the feedback that said it failed to deliver and so cannot be answered)
   */
  feedbackResponse?: FeedbackResponse;
  /**
   * Observation ID
   */
  id: string;
  /**
   * The next step the review wrote about this observation, whether or not the feedback carrying it was delivered (null when it wrote none)
   */
  nextStep?: string;
  /**
   * When the observation was made
   */
  observedAt: Date;
  /**
   * What occasioned the measurement; never mix origins in one trend line
   */
  origin: 'LIVE' | 'MANUAL' | 'BACKFILL';
  /**
   * Practice name
   */
  practiceName: string;
  /**
   * Practice slug
   */
  practiceSlug: string;
  /**
   * PRESENT or ABSENT only when ASSESSED
   */
  presence?: 'PRESENT' | 'ABSENT';
  /**
   * Cross-run locus key; null when continuity is unavailable
   */
  recurrenceKey?: string;
  /**
   * Severity level (null unless outcome is NEGATIVE)
   */
  severity?: 'CRITICAL' | 'MAJOR' | 'MINOR' | 'INFO';
  /**
   * Observation summary
   */
  summary: string;
};

/**
 * A complete review run in a developer's practice-group history
 */
export type PracticeGroupReviewRunWritable = {
  /**
   * Every visible observation of the run, complete enough to open in place
   */
  observations: Array<ObservationDetailWritable>;
  reviewId: string;
  reviewedAt: Date;
  reviewedWork: ReviewedWorkRef;
};

/**
 * A page of visible review runs
 */
export type PracticeGroupReviewRunsPageWritable = {
  content: Array<PracticeGroupReviewRunWritable>;
  hasNext?: boolean;
  page?: number;
  size?: number;
};

/**
 * A developer's derived qualitative standing for one Group including 1<=n<many practices
 */
export type PracticeGroupStandingWritable = {
  /**
   * Evidence-weighted, opportunity-indexed direction across the group's practices
   */
  direction?: 'IMPROVING' | 'DECLINING' | 'UNCERTAIN' | 'INSUFFICIENT_EVIDENCE';
  /**
   * Oldest contributing observation, for provenance only (null without a verdict)
   */
  feedbackSince?: Date;
  /**
   * Calendar span covered by the feedback, for provenance only; never a trend-analysis unit
   */
  feedbackSpanDays?: number;
  /**
   * Group name
   */
  groupName: string;
  /**
   * Group slug
   */
  groupSlug: string;
  /**
   * Developer guidance aggregated from the group's feedback (null unless the standing is a verdict). The deterministic summary combines standing, next focus, and developer-facing catalog guidance.
   */
  guidance?: string;
  /**
   * How the guidance text was produced (null when there is no guidance)
   */
  guidanceSource?: 'RULE_BASED';
  /**
   * Supporting observations the standing derives from (problems first); empty without a verdict
   */
  observations: Array<PracticeStandingObservationWritable>;
  /**
   * Distinct pieces of reviewed work the observations come from, per kind (provenance, not a score); empty without a verdict
   */
  sources: Array<FeedbackSourceCount>;
  /**
   * Derived qualitative standing across the group's practices
   */
  standing: 'DEVELOPING' | 'STRENGTH' | 'MIXED' | 'NOT_OBSERVED' | 'NO_OPPORTUNITY';
  /**
   * Evidence support and provenance for the direction
   */
  trendSupport?: TrendSupport;
};

/**
 * A developer's readable feedback for one practice
 */
export type PracticeStandingWritable = {
  /**
   * Opportunity-indexed direction of this practice's recent evidence
   */
  direction?: 'IMPROVING' | 'DECLINING' | 'UNCERTAIN' | 'INSUFFICIENT_EVIDENCE';
  /**
   * Group name this practice belongs to, if any
   */
  groupName?: string;
  /**
   * Group slug this practice belongs to, if any
   */
  groupSlug?: string;
  /**
   * Practice name
   */
  name: string;
  /**
   * Practice slug
   */
  slug: string;
  /**
   * Where the developer stands on this practice, or why no standing could be formed
   */
  standing: 'DEVELOPING' | 'STRENGTH' | 'MIXED' | 'NOT_OBSERVED' | 'NO_OPPORTUNITY';
  /**
   * What the developer already does well here
   */
  strengths: Array<PracticeStandingObservationWritable>;
  /**
   * Specific feedback to act on (highest-impact first)
   */
  toWorkOn: Array<PracticeStandingObservationWritable>;
  /**
   * Evidence support and provenance for the direction
   */
  trendSupport?: TrendSupport;
  /**
   * A concrete picture of doing this well
   */
  whatGoodLooksLike?: string;
  /**
   * Why this practice matters, in plain language
   */
  whyItMatters?: string;
};

/**
 * A single piece of practice feedback to read and act on
 */
export type PracticeStandingObservationWritable = {
  /**
   * What to do — the text of the newest feedback that said something about this observation to this developer (null if nothing was said)
   */
  deliveredFeedback?: string;
  /**
   * What this observation says about the developer: a behaviour demonstrated, a trap avoided, something harmful done, or something needed left out. The lists only separate positive from negative, so this is what tells the two kinds of each apart. Only assessed observations reach a standing, so NOT_APPLICABLE and UNDETERMINED never appear here.
   */
  kind: 'DEMONSTRATED_STRENGTH' | 'SAFE_AVOIDANCE' | 'COMMISSION_PROBLEM' | 'OMISSION_GAP' | 'NOT_APPLICABLE' | 'UNDETERMINED';
  /**
   * Where in the work, e.g. "FrameRecorder.swift:212", when known
   */
  locator?: string;
  /**
   * Observation id — handle to open the full detail
   */
  observationId: string;
  /**
   * Why this observation was recorded. BACKFILL means it came from a review of past work rather than from something that just happened, and nothing was posted anywhere at the time.
   */
  origin: 'LIVE' | 'MANUAL' | 'BACKFILL';
  /**
   * Identifier of the reviewed work
   */
  reviewedWorkId: number;
  /**
   * Impact level (null unless assessed BAD)
   */
  severity?: 'CRITICAL' | 'MAJOR' | 'MINOR' | 'INFO';
  /**
   * The headline of the feedback
   */
  title: string;
  /**
   * The kind of reviewed work this is about
   */
  workKind: string;
};

export type GetNativeClientConfigurationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/native/configuration';
};

export type GetNativeClientConfigurationResponses = {
  /**
   * OK
   */
  200: NativeClientConfiguration;
};

export type GetNativeClientConfigurationResponse = GetNativeClientConfigurationResponses[keyof GetNativeClientConfigurationResponses];

export type LogoutNativeSessionData = {
  body: NativeRefreshRequest;
  path?: never;
  query?: never;
  url: '/auth/native/logout';
};

export type LogoutNativeSessionResponses = {
  /**
   * Signed out, or the secret was already unknown
   */
  204: void;
};

export type LogoutNativeSessionResponse = LogoutNativeSessionResponses[keyof LogoutNativeSessionResponses];

export type RefreshNativeSessionData = {
  body: NativeRefreshRequest;
  path?: never;
  query?: never;
  url: '/auth/native/refresh';
};

export type RefreshNativeSessionErrors = {
  /**
   * The session has ended; sign in again
   */
  401: ProblemDetail;
};

export type RefreshNativeSessionError = RefreshNativeSessionErrors[keyof RefreshNativeSessionErrors];

export type RefreshNativeSessionResponses = {
  /**
   * Rotated
   */
  200: NativeSessionTokens;
};

export type RefreshNativeSessionResponse = RefreshNativeSessionResponses[keyof RefreshNativeSessionResponses];

export type ExchangeNativeSignInData = {
  body: NativeTokenRequest;
  path?: never;
  query?: never;
  url: '/auth/native/token';
};

export type ExchangeNativeSignInErrors = {
  /**
   * The code is unknown, expired, used, or does not match the verifier
   */
  400: NativeSessionTokens;
};

export type ExchangeNativeSignInError = ExchangeNativeSignInErrors[keyof ExchangeNativeSignInErrors];

export type ExchangeNativeSignInResponses = {
  /**
   * Signed in
   */
  200: NativeSessionTokens;
};

export type ExchangeNativeSignInResponse = ExchangeNativeSignInResponses[keyof ExchangeNativeSignInResponses];

export type ListIdentityProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/identity-providers';
};

export type ListIdentityProvidersResponses = {
  /**
   * OK
   */
  200: Array<IdentityProviderView>;
};

export type ListIdentityProvidersResponse = ListIdentityProvidersResponses[keyof ListIdentityProvidersResponses];

export type SubmitInstanceProductFeedbackData = {
  body: FeedbackRequest;
  path?: never;
  query?: never;
  url: '/product-feedback';
};

export type SubmitInstanceProductFeedbackResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteCurrentUserData = {
  body?: never;
  headers?: {
    'X-Confirm-Delete'?: string;
  };
  path?: never;
  query?: never;
  url: '/user';
};

export type DeleteCurrentUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user';
};

export type GetCurrentUserResponses = {
  /**
   * OK
   */
  200: CurrentUserView;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetConsentStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/consent';
};

export type GetConsentStatusResponses = {
  /**
   * OK
   */
  200: ConsentStatus;
};

export type GetConsentStatusResponse = GetConsentStatusResponses[keyof GetConsentStatusResponses];

export type CompleteFirstLoginConsentData = {
  body: FirstLoginConsent;
  path?: never;
  query?: never;
  url: '/user/consent';
};

export type CompleteFirstLoginConsentResponses = {
  /**
   * OK
   */
  200: ConsentStatus;
};

export type CompleteFirstLoginConsentResponse = CompleteFirstLoginConsentResponses[keyof CompleteFirstLoginConsentResponses];

export type UpdateResearchConsentData = {
  body: ResearchConsent;
  path?: never;
  query?: never;
  url: '/user/consent/research';
};

export type UpdateResearchConsentResponses = {
  /**
   * OK
   */
  200: ConsentStatus;
};

export type UpdateResearchConsentResponse = UpdateResearchConsentResponses[keyof UpdateResearchConsentResponses];

export type UnregisterPushDeviceData = {
  body?: never;
  path: {
    installationId: string;
  };
  query?: never;
  url: '/user/push-devices/{installationId}';
};

export type UnregisterPushDeviceResponses = {
  /**
   * Unregistered, or it was not registered
   */
  204: void;
};

export type UnregisterPushDeviceResponse = UnregisterPushDeviceResponses[keyof UnregisterPushDeviceResponses];

export type GetPushDeviceStatusData = {
  body?: never;
  path: {
    installationId: string;
  };
  query?: never;
  url: '/user/push-devices/{installationId}';
};

export type GetPushDeviceStatusResponses = {
  /**
   * OK
   */
  200: PushDeviceStatus;
};

export type GetPushDeviceStatusResponse = GetPushDeviceStatusResponses[keyof GetPushDeviceStatusResponses];

export type RegisterPushDeviceData = {
  body: PushDeviceRegistration;
  path: {
    installationId: string;
  };
  query?: never;
  url: '/user/push-devices/{installationId}';
};

export type RegisterPushDeviceErrors = {
  /**
   * Not a native app session
   */
  400: unknown;
  /**
   * This server does not send push notifications
   */
  409: unknown;
};

export type RegisterPushDeviceResponses = {
  /**
   * Registered
   */
  204: void;
};

export type RegisterPushDeviceResponse = RegisterPushDeviceResponses[keyof RegisterPushDeviceResponses];

export type RevokeOtherSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/sessions';
};

export type RevokeOtherSessionsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ListSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/sessions';
};

export type ListSessionsResponses = {
  /**
   * OK
   */
  200: Array<SessionView>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type RevokeSessionData = {
  body?: never;
  path: {
    jti: string;
  };
  query?: never;
  url: '/user/sessions/{jti}';
};

export type RevokeSessionResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ListWorkspacesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/workspaces';
};

export type ListWorkspacesResponses = {
  /**
   * Workspace list
   */
  200: Array<WorkspaceListItem>;
};

export type ListWorkspacesResponse = ListWorkspacesResponses[keyof ListWorkspacesResponses];

export type ListThreadsData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/mentor/threads';
};

export type ListThreadsResponses = {
  /**
   * Threads returned, newest first
   */
  200: Array<ChatThreadSummary>;
};

export type ListThreadsResponse = ListThreadsResponses[keyof ListThreadsResponses];

export type DeleteThreadData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    threadId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/mentor/threads/{threadId}';
};

export type DeleteThreadErrors = {
  /**
   * Thread not found OR not owned by current user
   */
  404: unknown;
};

export type DeleteThreadResponses = {
  /**
   * Thread deleted
   */
  204: void;
};

export type DeleteThreadResponse = DeleteThreadResponses[keyof DeleteThreadResponses];

export type GetThreadData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    threadId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/mentor/threads/{threadId}';
};

export type GetThreadErrors = {
  /**
   * Thread not found OR not owned by current user
   */
  404: unknown;
};

export type GetThreadResponses = {
  /**
   * Thread, messages and the owner's votes returned
   */
  200: ChatThreadDetail;
};

export type GetThreadResponse = GetThreadResponses[keyof GetThreadResponses];

export type ListGroupsData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
  };
  query?: {
    /**
     * Return only groups shown in practice dashboards
     */
    visibleInPracticeDashboardsOnly?: boolean;
  };
  url: '/workspaces/{workspaceSlug}/practice-groups';
};

export type ListGroupsResponses = {
  /**
   * Groups returned
   */
  200: Array<PracticeGroup>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type ListPracticeGroupStandingsData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practice-groups/standings';
};

export type ListPracticeGroupStandingsResponses = {
  /**
   * Practice group standings returned
   */
  200: Array<PracticeGroupStanding>;
};

export type ListPracticeGroupStandingsResponse = ListPracticeGroupStandingsResponses[keyof ListPracticeGroupStandingsResponses];

export type ListPracticeGroupReviewRunsData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    groupSlug: string;
  };
  query?: {
    practiceSlug?: string;
    /**
     * Only reviews of these artifact kinds, e.g. scm.pull_request (repeatable)
     */
    artifactKinds?: Array<string>;
    severities?: Array<'CRITICAL' | 'MAJOR' | 'MINOR' | 'INFO'>;
    /**
     * Zero-based page, at most 100
     */
    page?: number;
    /**
     * Page size from 1 to 50
     */
    size?: number;
  };
  url: '/workspaces/{workspaceSlug}/practice-groups/{groupSlug}/review-runs';
};

export type ListPracticeGroupReviewRunsErrors = {
  /**
   * Invalid filter or pagination
   */
  400: ProblemDetail;
  /**
   * Practice group not found
   */
  404: unknown;
};

export type ListPracticeGroupReviewRunsError = ListPracticeGroupReviewRunsErrors[keyof ListPracticeGroupReviewRunsErrors];

export type ListPracticeGroupReviewRunsResponses = {
  /**
   * Paginated review runs returned
   */
  200: PracticeGroupReviewRunsPage;
};

export type ListPracticeGroupReviewRunsResponse = ListPracticeGroupReviewRunsResponses[keyof ListPracticeGroupReviewRunsResponses];

export type GetInAppFeedbackData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/feedback/in-app';
};

export type GetInAppFeedbackResponses = {
  /**
   * In-app messages returned, newest first
   */
  200: Array<InAppFeedback>;
};

export type GetInAppFeedbackResponse = GetInAppFeedbackResponses[keyof GetInAppFeedbackResponses];

export type DeleteFeedbackResponseData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    feedbackId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/feedback/{feedbackId}/response';
};

export type DeleteFeedbackResponseErrors = {
  /**
   * Delivered feedback not found for the current recipient
   */
  404: unknown;
};

export type DeleteFeedbackResponseResponses = {
  /**
   * Response deleted or no response was recorded
   */
  204: void;
};

export type DeleteFeedbackResponseResponse = DeleteFeedbackResponseResponses[keyof DeleteFeedbackResponseResponses];

export type GetFeedbackResponseData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    feedbackId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/feedback/{feedbackId}/response';
};

export type GetFeedbackResponseErrors = {
  /**
   * Delivered feedback not found for the current recipient
   */
  404: unknown;
};

export type GetFeedbackResponseResponses = {
  /**
   * Current response returned
   */
  200: FeedbackResponse;
  /**
   * No response is currently recorded
   */
  204: void;
};

export type GetFeedbackResponseResponse = GetFeedbackResponseResponses[keyof GetFeedbackResponseResponses];

export type ReplaceFeedbackResponseData = {
  body: FeedbackResponseRequest;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    feedbackId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/feedback/{feedbackId}/response';
};

export type ReplaceFeedbackResponseErrors = {
  /**
   * Invalid response
   */
  400: unknown;
  /**
   * Delivered feedback not found for the current recipient
   */
  404: unknown;
};

export type ReplaceFeedbackResponseResponses = {
  /**
   * Response replaced
   */
  200: FeedbackResponse;
};

export type ReplaceFeedbackResponseResponse = ReplaceFeedbackResponseResponses[keyof ReplaceFeedbackResponseResponses];

export type GetObservationData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
    observationId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/observations/{observationId}';
};

export type GetObservationErrors = {
  /**
   * Observation not found or not owned by current user
   */
  404: unknown;
};

export type GetObservationResponses = {
  /**
   * Observation detail returned
   */
  200: ObservationDetail;
};

export type GetObservationResponse = GetObservationResponses[keyof GetObservationResponses];

export type ListReviewedPracticesData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/reviewed';
};

export type ListReviewedPracticesResponses = {
  /**
   * Developer practices returned
   */
  200: Array<ReviewedPractice>;
};

export type ListReviewedPracticesResponse = ListReviewedPracticesResponses[keyof ListReviewedPracticesResponses];

export type ListPracticeStandingsData = {
  body?: never;
  path: {
    /**
     * Workspace slug
     */
    workspaceSlug: string;
  };
  query?: never;
  url: '/workspaces/{workspaceSlug}/practices/standings';
};

export type ListPracticeStandingsResponses = {
  /**
   * Practice standings returned
   */
  200: Array<PracticeStanding>;
};

export type ListPracticeStandingsResponse = ListPracticeStandingsResponses[keyof ListPracticeStandingsResponses];
