import { ruleTester } from "../rule-tester.ts";
import { steUiText } from "./ste-ui-text.ts";

ruleTester.run("ste-ui-text", steUiText, {
	valid: [
		{ code: "<p>Fish &amp; chips</p>" },
		{ code: '<Input title="Fish &amp; chips" />' },
		{ code: '<p>{"utilize" && "Use it"}</p>' },
		{ code: "<p>Select the workspace.</p>" },
		{ code: '<input placeholder="Select a workspace" aria-label="Workspace" />' },
		{ code: '<div className="utilize" id="ensure" data-testid="via" />' },
		{ code: '<Link to="/utilize" href="/ensure" />' },
		{ code: 'const data = "utilize"; const a = <p>{data}</p>;' },
		{ code: '<p>{format("utilize")}</p>' },
		{ code: "<p>Use the workspace. Use the server.</p>" },
		{ code: "<style>{`a { color: red; }`}</style>" },
		{ code: 'toast.success("Saved the group.");' },
		{ code: "toast.error(message, { description: detail });" },
		{ code: 'toast.dismiss("Utilize");' },
		{ code: "<script>{`a; b`}</script>" },
		{ code: 'notify.error("Utilize it");' },
		{ code: 'const group = { slug: "utilize", label: "Group" };' },
		{ code: 'const x = { [label]: "Utilize it" };' },
		{
			code: "<p>Heph can record an observation.</p>",
			options: [{ vocabulary: true }],
		},
	],
	invalid: [
		{ code: "<p>Don&#39;t stop it.</p>", errors: [{ messageId: "word" }] },
		{ code: "<p>Utili&#122;e it.</p>", errors: [{ messageId: "word" }] },
		{ code: '<Input title="Utili&#122;e it" />', errors: [{ messageId: "word" }] },
		{ code: '<p>{"Fish &amp; chips"}</p>', errors: [{ messageId: "semicolon" }] },
		{
			code: "<p>We’re ready.</p>",
			errors: [{ messageId: "word", data: { from: "we’re", to: "we are" } }],
		},
		{
			code: "<p>It’s been stopped.</p>",
			errors: [{ messageId: "word", data: { from: "it’s", to: "it is or it has" } }],
		},
		{
			code: "<p>Utilize the workspace.</p>",
			errors: [{ messageId: "word", data: { from: "utilize", to: "use" } }],
		},
		{
			code: "<p>Ensure access prior to use.</p>",
			errors: [{ messageId: "word" }, { messageId: "word" }],
		},
		{ code: '<img alt="Utilize this icon" />', errors: [{ messageId: "word" }] },
		{
			code: '<Input placeholder={"Utilize a workspace"} />',
			errors: [{ messageId: "word" }],
		},
		{ code: '<p>{"Utilize a workspace"}</p>', errors: [{ messageId: "word" }] },
		{ code: '<p>{ok ? "Utilize it" : "Use it"}</p>', errors: [{ messageId: "word" }] },
		{ code: '<p>{ok && "Utilize it"}</p>', errors: [{ messageId: "word" }] },
		{ code: `<p>{\`Utilize \${name} now\`}</p>`, errors: [{ messageId: "word" }] },
		{ code: '<p>{"uti" + "lize it"}</p>', errors: [{ messageId: "word" }] },
		{ code: "<p>Do not start it; stop it.</p>", errors: [{ messageId: "semicolon" }] },
		{ code: "<p>Don’t stop it.</p>", errors: [{ messageId: "word" }] },
		{
			code: "<p>Use the server to check the workspace and then use the server to check the workspace and then use the server to check the workspace again.</p>",
			errors: [{ messageId: "sentence" }],
		},
		{
			code: "<p>Use the server to check the workspace and then use the server\n to check the workspace and then use the server to check the workspace again.</p>",
			errors: [{ messageId: "sentence" }],
		},
		{ code: 'toast.error("Couldn\'t save the group.");', errors: [{ messageId: "word" }] },
		{ code: 'toast("Utilize it");', errors: [{ messageId: "word" }] },
		{ code: "toast.warning(`Utilize ${name}`);", errors: [{ messageId: "word" }] },
		{
			code: 'toast.success("Saved", { description: "Don\'t stop; go." });',
			errors: [{ messageId: "word" }, { messageId: "semicolon" }],
		},
		{
			code: 'toast.promise(save, { loading: "Utilize it", success: "Utilize it", error: "Utilize it" });',
			errors: [{ messageId: "word" }, { messageId: "word" }, { messageId: "word" }],
		},
		...[
			"label",
			"description",
			"title",
			"message",
			"summary",
			"placeholder",
			"tooltip",
			"note",
			"content",
			"detail",
			"hint",
			"heading",
			"caption",
			"subtitle",
		].map((key) => ({
			code: `const group = { ${key}: "Utilize it" };`,
			errors: [{ messageId: "word" as const }],
		})),
		{ code: 'const group = { "title": "Utilize it" };', errors: [{ messageId: "word" }] },
		{
			code: "<p>Quux</p>",
			options: [{ vocabulary: true }],
			errors: [{ messageId: "vocabulary" }],
		},
	],
});
