import { ruleTester } from "../rule-tester.ts";
import { uiTextVoice } from "./ui-text-voice.ts";

ruleTester.run("ui-text-voice", uiTextVoice, {
	valid: [
		{ code: "<p>Fish &amp; chips</p>" },
		{ code: '<Input title="Fish &amp; chips" />' },
		{ code: '<p>{"utilize" && "Use it"}</p>' },
		{ code: "<p>Select the workspace.</p>" },
		{ code: '<input placeholder="Select a workspace" aria-label="Workspace" />' },
		{ code: '<div className="utilize" id="ensure" data-testid="via" />' },
		{ code: '<Link to="/utilize" href="/ensure" />' },
		{ code: 'const data = "utilize"; const a = <p>{data}</p>;' },
		{ code: '<p>{format("utilize")}</p>' },
		{ code: "<p>Use the workspace. Use the server.</p>" },
		{ code: "<style>{`a { color: red; }`}</style>" },
		{ code: 'toast.success("Saved the group.");' },
		{ code: "toast.error(message, { description: detail });" },
		{ code: 'toast.dismiss("Utilize");' },
		{ code: "<script>{`a; b`}</script>" },
		{ code: 'notify.error("Utilize it");' },
		{ code: 'const group = { slug: "utilize", label: "Group" };' },
		{ code: 'const x = { [label]: "Utilize it" };' },
		{ code: "<p>You’re set. We’ll tell you when it finishes.</p>" },
		{ code: "<p>Let’s connect a repository.</p>" },
		{ code: '<p title="It’s ready">That’s all.</p>' },
		{ code: 'toast.success("You’re signed in.");' },
		{ code: `<p>{\`It’s \${name}\`}</p>` },
		{ code: "<p>You are not a member. It is not saved.</p>" },
		{ code: "<p>The workspace’s practices.</p>" },
		{ code: '<meta name="viewport" content="width=device-width; initial-scale=1" />' },
		{ code: "<code>const a = 1;</code>" },
		{ code: '<pre>{"if (x) { y(); }"}</pre>' },
		{ code: "<p>Press <kbd>Ctrl+C</kbd>.</p>" },
		{ code: '<Dialog confirmLabel="Delete practice" emptyTitle="No practices yet" />' },
		{
			// Exactly 25 words is the longest sentence the rule accepts.
			code: "<p>One two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty twenty-one twenty-two twenty-three twenty-four twenty-five.</p>",
		},
	],
	invalid: [
		{
			code: '<Dialog confirmLabel="Don’t utilize it" />',
			errors: [{ messageId: "word" }, { messageId: "word" }],
		},
		{
			code: '<Empty emptyTitle="Can’t load; retry" />',
			errors: [{ messageId: "word" }, { messageId: "semicolon" }],
		},
		{ code: "<p>{name}'s plan</p>", errors: [{ messageId: "apostrophe", data: { found: "'s" } }] },
		{
			code: `<p>{\`\${name}'s plan\`}</p>`,
			errors: [{ messageId: "apostrophe" }],
		},
		{ code: "<p>Say 'hello'.</p>", errors: [{ messageId: "apostrophe" }] },
		{ code: "<p>You&#39;re set.</p>", errors: [{ messageId: "apostrophe" }] },
		{ code: "<p>The workspace's practices.</p>", errors: [{ messageId: "apostrophe" }] },
		{ code: 'toast.success("You\'re signed in.");', errors: [{ messageId: "apostrophe" }] },
		{
			code: "<p>Don&#39;t stop it.</p>",
			errors: [{ messageId: "word" }, { messageId: "apostrophe" }],
		},
		{ code: "<p>Utili&#122;e it.</p>", errors: [{ messageId: "word" }] },
		{ code: '<Input title="Utili&#122;e it" />', errors: [{ messageId: "word" }] },
		{ code: '<p>{"Fish &amp; chips"}</p>', errors: [{ messageId: "semicolon" }] },
		{
			code: "<p>You can’t undo this.</p>",
			errors: [{ messageId: "word", data: { from: "can’t", to: "cannot" } }],
		},
		{
			code: "<p>It won’t run.</p>",
			errors: [{ messageId: "word", data: { from: "won’t", to: "will not" } }],
		},
		{
			code: "<p>You’re set, but it isn’t saved.</p>",
			errors: [{ messageId: "word", data: { from: "isn’t", to: "is not" } }],
		},
		{
			code: "<p>Utilize the workspace.</p>",
			errors: [{ messageId: "word", data: { from: "utilize", to: "use" } }],
		},
		{
			code: "<p>Ensure access prior to use.</p>",
			errors: [{ messageId: "word" }, { messageId: "word" }],
		},
		{ code: '<img alt="Utilize this icon" />', errors: [{ messageId: "word" }] },
		{
			code: '<Input placeholder={"Utilize a workspace"} />',
			errors: [{ messageId: "word" }],
		},
		{ code: '<p>{"Utilize a workspace"}</p>', errors: [{ messageId: "word" }] },
		{ code: '<p>{ok ? "Utilize it" : "Use it"}</p>', errors: [{ messageId: "word" }] },
		{ code: '<p>{ok && "Utilize it"}</p>', errors: [{ messageId: "word" }] },
		{ code: `<p>{\`Utilize \${name} now\`}</p>`, errors: [{ messageId: "word" }] },
		{ code: '<p>{"uti" + "lize it"}</p>', errors: [{ messageId: "word" }] },
		{ code: "<p>Do not start it; stop it.</p>", errors: [{ messageId: "semicolon" }] },
		{ code: "<p>Don’t stop it.</p>", errors: [{ messageId: "word" }] },
		{
			code: "<p>Use the server to check the workspace and then use the server to check the workspace and then use the server to check the workspace again.</p>",
			errors: [{ messageId: "sentence" }],
		},
		{
			code: "<p>Use the server to check the workspace and then use the server\n to check the workspace and then use the server to check the workspace again.</p>",
			errors: [{ messageId: "sentence" }],
		},
		{ code: 'toast.error("Couldn’t save the group.");', errors: [{ messageId: "word" }] },
		{ code: 'toast("Utilize it");', errors: [{ messageId: "word" }] },
		{ code: `toast.warning(\`Utilize \${name}\`);`, errors: [{ messageId: "word" }] },
		{
			code: 'toast.success("Saved", { description: "Don’t stop; go." });',
			errors: [{ messageId: "word" }, { messageId: "semicolon" }],
		},
		{
			code: 'toast.promise(save, { loading: "Utilize it", success: "Utilize it", error: "Utilize it" });',
			errors: [{ messageId: "word" }, { messageId: "word" }, { messageId: "word" }],
		},
		...[
			"label",
			"description",
			"title",
			"message",
			"summary",
			"placeholder",
			"tooltip",
			"note",
			"content",
			"detail",
			"hint",
			"heading",
			"caption",
			"subtitle",
		].map((key) => ({
			code: `const group = { ${key}: "Utilize it" };`,
			errors: [{ messageId: "word" as const }],
		})),
		{ code: 'const group = { "title": "Utilize it" };', errors: [{ messageId: "word" }] },
	],
});
