// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { completeFirstLoginConsent, deleteCurrentUser, deleteFeedbackResponse, deleteThread, exchangeNativeSignIn, getConsentStatus, getCurrentUser, getFeedbackResponse, getInAppFeedback, getNativeClientConfiguration, getObservation, getPushDeviceStatus, getThread, listGroups, listIdentityProviders, listPracticeGroupReviewRuns, listPracticeGroupStandings, listPracticeStandings, listReviewedPractices, listSessions, listThreads, listWorkspaces, logoutNativeSession, type Options, refreshNativeSession, registerPushDevice, replaceFeedbackResponse, revokeOtherSessions, revokeSession, submitInstanceProductFeedback, unregisterPushDevice, updateResearchConsent } from '../sdk.gen';
import type { CompleteFirstLoginConsentData, CompleteFirstLoginConsentResponse, DeleteCurrentUserData, DeleteFeedbackResponseData, DeleteFeedbackResponseResponse, DeleteThreadData, DeleteThreadResponse, ExchangeNativeSignInData, ExchangeNativeSignInError, ExchangeNativeSignInResponse, GetConsentStatusData, GetConsentStatusResponse, GetCurrentUserData, GetCurrentUserResponse, GetFeedbackResponseData, GetFeedbackResponseResponse, GetInAppFeedbackData, GetInAppFeedbackResponse, GetNativeClientConfigurationData, GetNativeClientConfigurationResponse, GetObservationData, GetObservationResponse, GetPushDeviceStatusData, GetPushDeviceStatusResponse, GetThreadData, GetThreadResponse, ListGroupsData, ListGroupsResponse, ListIdentityProvidersData, ListIdentityProvidersResponse, ListPracticeGroupReviewRunsData, ListPracticeGroupReviewRunsError, ListPracticeGroupReviewRunsResponse, ListPracticeGroupStandingsData, ListPracticeGroupStandingsResponse, ListPracticeStandingsData, ListPracticeStandingsResponse, ListReviewedPracticesData, ListReviewedPracticesResponse, ListSessionsData, ListSessionsResponse, ListThreadsData, ListThreadsResponse, ListWorkspacesData, ListWorkspacesResponse, LogoutNativeSessionData, LogoutNativeSessionResponse, RefreshNativeSessionData, RefreshNativeSessionError, RefreshNativeSessionResponse, RegisterPushDeviceData, RegisterPushDeviceResponse, ReplaceFeedbackResponseData, ReplaceFeedbackResponseResponse, RevokeOtherSessionsData, RevokeSessionData, SubmitInstanceProductFeedbackData, UnregisterPushDeviceData, UnregisterPushDeviceResponse, UpdateResearchConsentData, UpdateResearchConsentResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
  QueryKey<TOptions>[0]
] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getNativeClientConfigurationQueryKey = (options?: Options<GetNativeClientConfigurationData>) => createQueryKey('getNativeClientConfiguration', options, false, ['Native session']);

/**
 * What this server requires of the native app
 *
 * Public. An app that finds no such endpoint is talking to a server without native sign-in.
 */
export const getNativeClientConfigurationOptions = (options?: Options<GetNativeClientConfigurationData>) => queryOptions<GetNativeClientConfigurationResponse, DefaultError, GetNativeClientConfigurationResponse, ReturnType<typeof getNativeClientConfigurationQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getNativeClientConfiguration({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getNativeClientConfigurationQueryKey(options)
});

/**
 * End the native session its refresh secret belongs to
 */
export const logoutNativeSessionMutation = (options?: Partial<Options<LogoutNativeSessionData>>): UseMutationOptions<LogoutNativeSessionResponse, DefaultError, Options<LogoutNativeSessionData>> => {
  const mutationOptions: UseMutationOptions<LogoutNativeSessionResponse, DefaultError, Options<LogoutNativeSessionData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutNativeSession({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

/**
 * Rotate the native session's access token and refresh secret
 */
export const refreshNativeSessionMutation = (options?: Partial<Options<RefreshNativeSessionData>>): UseMutationOptions<RefreshNativeSessionResponse, RefreshNativeSessionError, Options<RefreshNativeSessionData>> => {
  const mutationOptions: UseMutationOptions<RefreshNativeSessionResponse, RefreshNativeSessionError, Options<RefreshNativeSessionData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshNativeSession({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

/**
 * Redeem a sign-in handoff code with its PKCE verifier
 */
export const exchangeNativeSignInMutation = (options?: Partial<Options<ExchangeNativeSignInData>>): UseMutationOptions<ExchangeNativeSignInResponse, ExchangeNativeSignInError, Options<ExchangeNativeSignInData>> => {
  const mutationOptions: UseMutationOptions<ExchangeNativeSignInResponse, ExchangeNativeSignInError, Options<ExchangeNativeSignInData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await exchangeNativeSignIn({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const listIdentityProvidersQueryKey = (options?: Options<ListIdentityProvidersData>) => createQueryKey('listIdentityProviders', options, false, ['Auth discovery']);

/**
 * List available identity providers
 */
export const listIdentityProvidersOptions = (options?: Options<ListIdentityProvidersData>) => queryOptions<ListIdentityProvidersResponse, DefaultError, ListIdentityProvidersResponse, ReturnType<typeof listIdentityProvidersQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listIdentityProviders({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listIdentityProvidersQueryKey(options)
});

/**
 * Send instance-scoped product feedback
 */
export const submitInstanceProductFeedbackMutation = (options?: Partial<Options<SubmitInstanceProductFeedbackData>>): UseMutationOptions<unknown, DefaultError, Options<SubmitInstanceProductFeedbackData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SubmitInstanceProductFeedbackData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await submitInstanceProductFeedback({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

/**
 * Delete the current account (GDPR Art. 17)
 */
export const deleteCurrentUserMutation = (options?: Partial<Options<DeleteCurrentUserData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteCurrentUserData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteCurrentUserData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteCurrentUser({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options, false, ['Account']);

/**
 * Get the current user
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getCurrentUser({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getCurrentUserQueryKey(options)
});

export const getConsentStatusQueryKey = (options?: Options<GetConsentStatusData>) => createQueryKey('getConsentStatus', options, false, ['Consent']);

/**
 * Get the current consent notice and status
 */
export const getConsentStatusOptions = (options?: Options<GetConsentStatusData>) => queryOptions<GetConsentStatusResponse, DefaultError, GetConsentStatusResponse, ReturnType<typeof getConsentStatusQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getConsentStatus({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getConsentStatusQueryKey(options)
});

/**
 * Complete the first-login transparency step
 */
export const completeFirstLoginConsentMutation = (options?: Partial<Options<CompleteFirstLoginConsentData>>): UseMutationOptions<CompleteFirstLoginConsentResponse, DefaultError, Options<CompleteFirstLoginConsentData>> => {
  const mutationOptions: UseMutationOptions<CompleteFirstLoginConsentResponse, DefaultError, Options<CompleteFirstLoginConsentData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await completeFirstLoginConsent({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

/**
 * Grant or withdraw research consent
 */
export const updateResearchConsentMutation = (options?: Partial<Options<UpdateResearchConsentData>>): UseMutationOptions<UpdateResearchConsentResponse, DefaultError, Options<UpdateResearchConsentData>> => {
  const mutationOptions: UseMutationOptions<UpdateResearchConsentResponse, DefaultError, Options<UpdateResearchConsentData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateResearchConsent({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

/**
 * Stop push notifications on this installation
 */
export const unregisterPushDeviceMutation = (options?: Partial<Options<UnregisterPushDeviceData>>): UseMutationOptions<UnregisterPushDeviceResponse, DefaultError, Options<UnregisterPushDeviceData>> => {
  const mutationOptions: UseMutationOptions<UnregisterPushDeviceResponse, DefaultError, Options<UnregisterPushDeviceData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await unregisterPushDevice({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const getPushDeviceStatusQueryKey = (options: Options<GetPushDeviceStatusData>) => createQueryKey('getPushDeviceStatus', options, false, ['Push devices']);

/**
 * Whether this server sends push notifications and this installation receives them
 */
export const getPushDeviceStatusOptions = (options: Options<GetPushDeviceStatusData>) => queryOptions<GetPushDeviceStatusResponse, DefaultError, GetPushDeviceStatusResponse, ReturnType<typeof getPushDeviceStatusQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getPushDeviceStatus({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getPushDeviceStatusQueryKey(options)
});

/**
 * Receive push notifications on this installation
 */
export const registerPushDeviceMutation = (options?: Partial<Options<RegisterPushDeviceData>>): UseMutationOptions<RegisterPushDeviceResponse, DefaultError, Options<RegisterPushDeviceData>> => {
  const mutationOptions: UseMutationOptions<RegisterPushDeviceResponse, DefaultError, Options<RegisterPushDeviceData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await registerPushDevice({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

/**
 * Revoke all sessions except the current one
 */
export const revokeOtherSessionsMutation = (options?: Partial<Options<RevokeOtherSessionsData>>): UseMutationOptions<unknown, DefaultError, Options<RevokeOtherSessionsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RevokeOtherSessionsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeOtherSessions({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const listSessionsQueryKey = (options?: Options<ListSessionsData>) => createQueryKey('listSessions', options, false, ['Account']);

/**
 * List active sessions for the current user
 */
export const listSessionsOptions = (options?: Options<ListSessionsData>) => queryOptions<ListSessionsResponse, DefaultError, ListSessionsResponse, ReturnType<typeof listSessionsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listSessions({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listSessionsQueryKey(options)
});

/**
 * Revoke a single session
 */
export const revokeSessionMutation = (options?: Partial<Options<RevokeSessionData>>): UseMutationOptions<unknown, DefaultError, Options<RevokeSessionData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RevokeSessionData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeSession({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const listWorkspacesQueryKey = (options?: Options<ListWorkspacesData>) => createQueryKey('listWorkspaces', options, false, ['workspace-registry']);

/**
 * List all workspaces
 */
export const listWorkspacesOptions = (options?: Options<ListWorkspacesData>) => queryOptions<ListWorkspacesResponse, DefaultError, ListWorkspacesResponse, ReturnType<typeof listWorkspacesQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listWorkspaces({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listWorkspacesQueryKey(options)
});

export const listThreadsQueryKey = (options: Options<ListThreadsData>) => createQueryKey('listThreads', options, false, ['Mentor Threads']);

/**
 * List the current user's mentor threads in this workspace
 */
export const listThreadsOptions = (options: Options<ListThreadsData>) => queryOptions<ListThreadsResponse, DefaultError, ListThreadsResponse, ReturnType<typeof listThreadsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listThreads({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listThreadsQueryKey(options)
});

/**
 * Delete a mentor thread (cascades to messages, votes, parts)
 */
export const deleteThreadMutation = (options?: Partial<Options<DeleteThreadData>>): UseMutationOptions<DeleteThreadResponse, DefaultError, Options<DeleteThreadData>> => {
  const mutationOptions: UseMutationOptions<DeleteThreadResponse, DefaultError, Options<DeleteThreadData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteThread({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const getThreadQueryKey = (options: Options<GetThreadData>) => createQueryKey('getThread', options, false, ['Mentor Threads']);

/**
 * Get a mentor thread with its full message history
 */
export const getThreadOptions = (options: Options<GetThreadData>) => queryOptions<GetThreadResponse, DefaultError, GetThreadResponse, ReturnType<typeof getThreadQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getThread({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getThreadQueryKey(options)
});

export const listGroupsQueryKey = (options: Options<ListGroupsData>) => createQueryKey('listGroups', options, false, ['Practice Groups']);

/**
 * List practice groups
 *
 * Returns the workspace's practice groups
 */
export const listGroupsOptions = (options: Options<ListGroupsData>) => queryOptions<ListGroupsResponse, DefaultError, ListGroupsResponse, ReturnType<typeof listGroupsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listGroups({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listGroupsQueryKey(options)
});

export const listPracticeGroupStandingsQueryKey = (options: Options<ListPracticeGroupStandingsData>) => createQueryKey('listPracticeGroupStandings', options, false, ['Practice Group Standings']);

/**
 * List the current developer's practice group standings
 *
 * Returns every active practice group's standing, direction, guidance, and supporting observations.
 */
export const listPracticeGroupStandingsOptions = (options: Options<ListPracticeGroupStandingsData>) => queryOptions<ListPracticeGroupStandingsResponse, DefaultError, ListPracticeGroupStandingsResponse, ReturnType<typeof listPracticeGroupStandingsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listPracticeGroupStandings({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listPracticeGroupStandingsQueryKey(options)
});

export const listPracticeGroupReviewRunsQueryKey = (options: Options<ListPracticeGroupReviewRunsData>) => createQueryKey('listPracticeGroupReviewRuns', options, false, ['Practice Group Detail']);

/**
 * List complete review runs for a practice group
 *
 * Returns complete review runs newest first, including visible undecided observations.
 */
export const listPracticeGroupReviewRunsOptions = (options: Options<ListPracticeGroupReviewRunsData>) => queryOptions<ListPracticeGroupReviewRunsResponse, ListPracticeGroupReviewRunsError, ListPracticeGroupReviewRunsResponse, ReturnType<typeof listPracticeGroupReviewRunsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listPracticeGroupReviewRuns({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listPracticeGroupReviewRunsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...queryKey[0].body as any,
      ...page.body as any
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path as any,
      ...page.path as any
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query as any,
      ...page.query as any
    };
  }
  return params as unknown as typeof page;
};

export const listPracticeGroupReviewRunsInfiniteQueryKey = (options: Options<ListPracticeGroupReviewRunsData>): QueryKey<Options<ListPracticeGroupReviewRunsData>> => createQueryKey('listPracticeGroupReviewRuns', options, true);

/**
 * List complete review runs for a practice group
 *
 * Returns complete review runs newest first, including visible undecided observations.
 */
export const listPracticeGroupReviewRunsInfiniteOptions = (options: Options<ListPracticeGroupReviewRunsData>) => {
  const opts = infiniteQueryOptions<ListPracticeGroupReviewRunsResponse, ListPracticeGroupReviewRunsError, InfiniteData<ListPracticeGroupReviewRunsResponse>, QueryKey<Options<ListPracticeGroupReviewRunsData>>, number | Pick<QueryKey<Options<ListPracticeGroupReviewRunsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
  // @ts-ignore
  {
    queryFn: async ({ pageParam, queryKey, signal }) => {
      // @ts-ignore
      const page: Pick<QueryKey<Options<ListPracticeGroupReviewRunsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
        query: {
          page: pageParam
        }
      };
      const params = createInfiniteParams(queryKey, page);
      const { data } = await listPracticeGroupReviewRuns({
        ...options,
        ...params,
        signal,
        throwOnError: true
      });
      return data;
    },
    queryKey: listPracticeGroupReviewRunsInfiniteQueryKey(options)
  });
  return opts as Omit<typeof opts, 'initialData'>;
};

export const getInAppFeedbackQueryKey = (options: Options<GetInAppFeedbackData>) => createQueryKey('getInAppFeedback', options, false, ['In-App Feedback']);

/**
 * The current developer's in-app feedback
 *
 * Process-level messages prepared for the authenticated developer: for each way of working that recurs in their work, what the pattern is, the pieces of work it was observed on, and one thing to try next. Distinct from in-context notes (which say what is wrong in one diff) and from the mentor conversation (which asks rather than tells). Reading a message is what delivers it, so this GET records the delivery.
 */
export const getInAppFeedbackOptions = (options: Options<GetInAppFeedbackData>) => queryOptions<GetInAppFeedbackResponse, DefaultError, GetInAppFeedbackResponse, ReturnType<typeof getInAppFeedbackQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getInAppFeedback({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getInAppFeedbackQueryKey(options)
});

/**
 * Delete the response to delivered feedback
 */
export const deleteFeedbackResponseMutation = (options?: Partial<Options<DeleteFeedbackResponseData>>): UseMutationOptions<DeleteFeedbackResponseResponse, DefaultError, Options<DeleteFeedbackResponseData>> => {
  const mutationOptions: UseMutationOptions<DeleteFeedbackResponseResponse, DefaultError, Options<DeleteFeedbackResponseData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteFeedbackResponse({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const getFeedbackResponseQueryKey = (options: Options<GetFeedbackResponseData>) => createQueryKey('getFeedbackResponse', options, false, ['Feedback Response']);

/**
 * Get the current feedback response
 */
export const getFeedbackResponseOptions = (options: Options<GetFeedbackResponseData>) => queryOptions<GetFeedbackResponseResponse, DefaultError, GetFeedbackResponseResponse, ReturnType<typeof getFeedbackResponseQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getFeedbackResponse({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getFeedbackResponseQueryKey(options)
});

/**
 * Replace the response to delivered feedback
 *
 * Sets the complete current response. Repeating the same request has no effect.
 */
export const replaceFeedbackResponseMutation = (options?: Partial<Options<ReplaceFeedbackResponseData>>): UseMutationOptions<ReplaceFeedbackResponseResponse, DefaultError, Options<ReplaceFeedbackResponseData>> => {
  const mutationOptions: UseMutationOptions<ReplaceFeedbackResponseResponse, DefaultError, Options<ReplaceFeedbackResponseData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await replaceFeedbackResponse({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

export const getObservationQueryKey = (options: Options<GetObservationData>) => createQueryKey('getObservation', options, false, ['Practice Observations']);

/**
 * Get observation detail
 */
export const getObservationOptions = (options: Options<GetObservationData>) => queryOptions<GetObservationResponse, DefaultError, GetObservationResponse, ReturnType<typeof getObservationQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getObservation({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getObservationQueryKey(options)
});

export const listReviewedPracticesQueryKey = (options: Options<ListReviewedPracticesData>) => createQueryKey('listReviewedPractices', options, false, ['Practice Catalog']);

/**
 * List reviewed practices, developer-facing
 *
 * Returns the developer-facing name, group, rationale, and example for every practice the workspace reviews (any autonomy above OFF)
 */
export const listReviewedPracticesOptions = (options: Options<ListReviewedPracticesData>) => queryOptions<ListReviewedPracticesResponse, DefaultError, ListReviewedPracticesResponse, ReturnType<typeof listReviewedPracticesQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listReviewedPractices({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listReviewedPracticesQueryKey(options)
});

export const listPracticeStandingsQueryKey = (options: Options<ListPracticeStandingsData>) => createQueryKey('listPracticeStandings', options, false, ['Practice Standings']);

/**
 * List the current developer's practice standings
 *
 * Returns each practice's standing, direction, supporting observations, and developer guidance.
 */
export const listPracticeStandingsOptions = (options: Options<ListPracticeStandingsData>) => queryOptions<ListPracticeStandingsResponse, DefaultError, ListPracticeStandingsResponse, ReturnType<typeof listPracticeStandingsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listPracticeStandings({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listPracticeStandingsQueryKey(options)
});
