query GetGroupMembers($fullPath: ID!, $relations: [GroupMemberRelation!]!, $first: Int!, $after: String) {
    group(fullPath: $fullPath) {
        groupMembers(first: $first, after: $after, relations: $relations) {
            pageInfo {
                hasNextPage
                endCursor
            }
            nodes {
                user {
                    ...GitLabUserFields
                }
                accessLevel {
                    stringValue
                    integerValue
                }
            }
        }
    }
}
