query GetProjectsByIds($ids: [ID!]!) {
    projects(ids: $ids, first: 1) {
        nodes {
            id
            fullPath
            name
            webUrl
            description
            visibility
            archived
            createdAt
            lastActivityAt
            group {
                id
                fullPath
                name
                avatarUrl
                webUrl
                description
                visibility
            }
            repository {
                rootRef
            }
        }
    }
}
