// Runtime environment configuration (single source of truth)
// - Dev: uses defaults below
// - Prod: reads from window.__ENV__ (generated by docker/entrypoint.sh)
//
// To add a new variable:
// 1. Add to RuntimeEnvVars interface
// 2. Add to defaults object
// 3. Use via env("VAR_NAME") in the environment object
// The entrypoint.sh automatically extracts vars from this file.

declare global {
	interface Window {
		__ENV__?: RuntimeEnvVars;
	}
}

interface RuntimeEnvVars {
	APPLICATION_VERSION?: string;
	APPLICATION_CLIENT_URL?: string;
	APPLICATION_SERVER_URL?: string;
	XSRF_COOKIE_NAME?: string;
	SENTRY_ENVIRONMENT?: string;
	SENTRY_DSN?: string;
	LEGAL_PROFILE?: string;
	TANSTACK_DEVTOOLS_ENABLED?: string;
	GIT_BRANCH?: string;
	GIT_COMMIT?: string;
	DEPLOYED_AT?: string;
}

/**
 * The name the server gives the CSRF double-submit cookie when `hephaestus.auth.cookie-secure` is
 * on, which the `prod` profile requires of itself and every deployment runs under. A blank name
 * matches no cookie, so it is a variable that was never set rather than a choice — unlike
 * `SENTRY_DSN`, where blank deliberately turns reporting off. The entrypoint writes every key of
 * `RuntimeEnvVars` into `window.__ENV__` whether the container has it or not, so an unset variable
 * arrives as `""`, which no default beside it can rescue.
 */
const SECURE_XSRF_COOKIE_NAME = "__Host-XSRF-TOKEN";

// Dev defaults (used when window.__ENV__ is not set)
const defaults: RuntimeEnvVars = {
	APPLICATION_VERSION: "DEV",
	APPLICATION_CLIENT_URL: "http://localhost:4200",
	APPLICATION_SERVER_URL: "http://localhost:8080",
	XSRF_COOKIE_NAME: SECURE_XSRF_COOKIE_NAME,
	SENTRY_ENVIRONMENT: "local",
	SENTRY_DSN: "https://289f1f62feeb4f70a8878dc0101825cd@sentry.ase.in.tum.de/3",
	LEGAL_PROFILE: "",
	TANSTACK_DEVTOOLS_ENABLED: "true",
	GIT_BRANCH: "",
	GIT_COMMIT: "",
	DEPLOYED_AT: "",
};

const env = (key: keyof RuntimeEnvVars): string => window.__ENV__?.[key] ?? defaults[key] ?? "";

const DEPLOYMENT_NAMES: Record<string, string> = {
	production: "Production",
	staging: "Staging",
	preview: "Preview",
	local: "Local",
};
const deploymentEnvironment = env("SENTRY_ENVIRONMENT") || "local";

/**
 * Which pull request this preview is of. Every preview shares the name "Preview", so without this
 * the header pill cannot say which one you are looking at.
 *
 * Coolify routes a preview at `pr<id>.<domain>` and passes no pull request variable of its own, so
 * the hostname is where the number is — and the client URL is the one place that hostname is
 * already present in the runtime config. Read only on a preview, so no other deployment can be
 * given a pull request by a host that happens to be named this way.
 */
const previewPullRequest = ((): number | undefined => {
	if (deploymentEnvironment !== "preview") return undefined;
	try {
		const [label] = new URL(env("APPLICATION_CLIENT_URL")).hostname.split(".");
		const match = /^pr-?(\d+)$/.exec(label ?? "");
		return match ? Number.parseInt(match[1] ?? "", 10) : undefined;
	} catch {
		return undefined;
	}
})();

const environment = {
	version: env("APPLICATION_VERSION").replace(/^v/, "") || "DEV",
	deployment: {
		environment: deploymentEnvironment,
		name: DEPLOYMENT_NAMES[deploymentEnvironment] ?? "Local",
		isProduction: deploymentEnvironment === "production",
		pullRequest: previewPullRequest,
	},
	clientUrl: env("APPLICATION_CLIENT_URL"),
	serverUrl: env("APPLICATION_SERVER_URL"),
	// CSRF double-submit cookie name. `__Host-`-prefixed in production; dropped for local http E2E
	// (the browser rejects `__Host-` cookies over http://localhost) — must match the server's
	// hephaestus.auth.cookie-secure setting.
	xsrfCookieName: env("XSRF_COOKIE_NAME") || SECURE_XSRF_COOKIE_NAME,

	buildInfo: {
		branch: env("GIT_BRANCH"),
		commit: env("GIT_COMMIT"),
		deployedAt: env("DEPLOYED_AT"),
	},

	sentry: {
		environment: env("SENTRY_ENVIRONMENT"),
		dsn: env("SENTRY_DSN"),
	},

	legal: {
		profile: env("LEGAL_PROFILE"),
	},

	devtools: {
		tanstack: env("TANSTACK_DEVTOOLS_ENABLED") === "true",
	},
};

export default environment;
