package de.tum.cit.aet.hephaestus.integration.core.connection;

import de.tum.cit.aet.hephaestus.core.privacy.spi.*;
import de.tum.cit.aet.hephaestus.core.runtime.ConditionalOnServerRole;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Component;
import tools.jackson.databind.ObjectMapper;

@Component
@ConditionalOnServerRole
@RequiredArgsConstructor
@PersonDataStores({
    "user",
    "organization_membership",
    "team_membership",
    "repository_collaborator",
    "issue_assignee",
    "pull_request_requested_reviewers",
    "organization",
    "team",
    "team_repository_permission",
    "repository",
    "milestone",
    "issue_comment",
    "pull_request_review",
    "pull_request_review_comment",
    "discussion_comment",
    "issue",
    "pull_request_review_thread",
    "discussion",
    "git_commit",
    "commit_contributor",
    "commit_file_change",
    "project",
    "project_item",
    "project_status_update",
    "project_field_value",
    "connection_audit",
    "sync_job",
    "artifact_signal"
})
public class IntegrationCoreConnectionPersonDataCatalog implements PersonDataCatalog {
    private final NamedParameterJdbcTemplate jdbc;
    private final ObjectMapper mapper;

    @Override
    public List<PersonDataContributor> contributors() {
        return List.of(
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "user",
                        "user",
                        "t.id IN (:users)",
                        "id,created_at,updated_at,avatar_url,email,html_url,login,name,type,native_id,provider_id",
                        "id",
                        "login='erased-'||t.id::text,name=NULL,email=NULL,avatar_url='',html_url=''",
                        700),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "organization_membership",
                        "organization_membership",
                        "t.user_id IN (:users)",
                        "organization_id,user_id,role",
                        "organization_id,user_id",
                        "",
                        100),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "team_membership",
                        "team_membership",
                        "t.user_id IN (:users)",
                        "role,user_id,team_id",
                        "user_id,team_id",
                        "",
                        100),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "repository_collaborator",
                        "repository_collaborator",
                        "t.user_id IN (:users)",
                        "repository_id,user_id,permission",
                        "repository_id,user_id",
                        "",
                        100),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "issue_assignee",
                        "issue_assignee",
                        "t.user_id IN (:users)",
                        "issue_id,user_id",
                        "issue_id,user_id",
                        "",
                        100),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "pull_request_requested_reviewers",
                        "pull_request_requested_reviewers",
                        "t.user_id IN (:users)",
                        "pull_request_id,user_id,review_state",
                        "pull_request_id,user_id",
                        "",
                        100),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "organization",
                        "organization",
                        "FALSE",
                        "id,created_at,updated_at,avatar_url,native_id,html_url,login,name,last_sync_at,provider_id",
                        "id",
                        "",
                        0),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "team",
                        "team",
                        "FALSE",
                        "id,name,created_at,description,html_url,last_sync_at,organization,parent_id,privacy,updated_at,native_id,provider_id,slug",
                        "id",
                        "",
                        0),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "team_repository_permission",
                        "team_repository_permission",
                        "FALSE",
                        "permission,repository_id,team_id",
                        "repository_id,team_id",
                        "",
                        0),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "repository",
                        "repository",
                        "FALSE",
                        "id,created_at,updated_at,default_branch,description,html_url,is_archived,is_disabled,is_private,name,name_with_owner,pushed_at,visibility,organization_id,last_sync_at,has_discussions_enabled,native_id,provider_id",
                        "id",
                        "",
                        0),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "milestone",
                        "milestone",
                        "FALSE",
                        "id,created_at,updated_at,closed_at,due_on,html_url,number,state,title,creator_id,repository_id,description,closed_issues_count,open_issues_count,last_sync_at,native_id,provider_id",
                        "id",
                        "",
                        0),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "issue_comment",
                        "issue_comment",
                        "t.author_id IN (:users)",
                        "id,created_at,updated_at,author_association,html_url,author_id,issue_id,body,native_id,provider_id",
                        "id",
                        "author_id=NULL,body=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "pull_request_review",
                        "pull_request_review",
                        "t.author_id IN (:users)",
                        "id,commit_id,html_url,is_dismissed,state,submitted_at,author_id,pull_request_id,body,created_at,updated_at,author_can_push_to_repository,native_id,provider_id",
                        "id",
                        "author_id=NULL,body=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "pull_request_review_comment",
                        "pull_request_review_comment",
                        "t.author_id IN (:users)",
                        "id,created_at,updated_at,author_association,commit_id,html_url,line,original_commit_id,original_line,original_start_line,path,start_line,author_id,pull_request_id,review_id,thread_id,in_reply_to_id,body,diff_hunk,outdated,native_id,provider_id,side,start_side",
                        "id",
                        "author_id=NULL,body=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "discussion_comment",
                        "discussion_comment",
                        "t.author_id IN (:users)",
                        "id,created_at,updated_at,body,html_url,is_answer,is_minimized,minimized_reason,author_association,last_sync_at,discussion_id,author_id,parent_comment_id,native_id,provider_id",
                        "id",
                        "author_id=NULL,body=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "issue",
                        "issue",
                        "t.author_id IN (:users)",
                        "issue_type,id,created_at,updated_at,closed_at,comments_count,html_url,is_locked,number,state,title,additions,changed_files,commits,deletions,is_draft,is_merged,merged_at,author_id,milestone_id,repository_id,merged_by_id,last_sync_at,state_reason,body,parent_issue_id,sub_issues_total,sub_issues_completed,sub_issues_percent_completed,issue_type_id,merge_state_status,mergeable,review_decision,head_ref_name,head_ref_oid,base_ref_name,base_ref_oid,native_id,provider_id,merge_commit_sha,deleted_at,head_check_sha,head_check_state,review_snapshot_id,review_snapshot_digest,reviewers_observed_at,head_check_observed_at,discussions_observed_at",
                        "id",
                        "author_id=NULL,body=NULL,title='Erased work',html_url=NULL",
                        250),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "pull_request_review_thread",
                        "pull_request_review_thread",
                        "t.resolved_by_id IN (:users)",
                        "id,created_at,updated_at,state,pull_request_id,root_comment_id,node_id,path,line,start_line,side,start_side,outdated,collapsed,resolved_by_id,native_id,provider_id,commit_sha,original_commit_sha,resolved_at",
                        "id",
                        "resolved_by_id=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "discussion",
                        "discussion",
                        "t.author_id IN (:users)",
                        "id,created_at,updated_at,number,title,body,html_url,state,state_reason,upvote_count,is_locked,active_lock_reason,closed_at,answer_chosen_at,comment_count,last_sync_at,repository_id,author_id,category_id,answer_chosen_by_id,answer_comment_id,native_id,provider_id",
                        "id",
                        "author_id=NULL,body=NULL,title='Erased work',html_url=NULL",
                        250),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "git_commit",
                        "git_commit",
                        "t.author_id IN (:users) OR t.committer_id IN (:users)",
                        "id,sha,message,message_body,html_url,authored_at,committed_at,additions,deletions,changed_files,author_email,committer_email,signature_valid,authored_by_committer,committed_via_web,parent_count,last_sync_at,created_at,updated_at,repository_id,author_id,committer_id,signature_state,signature_was_signed_by_github,signature_signer_login,parent_shas,status_check_rollup_state,on_behalf_of_login,git_details_captured_at",
                        "id",
                        "author_id=NULL,committer_id=NULL,author_email=NULL,committer_email=NULL,message='',message_body=NULL,on_behalf_of_login=NULL,signature_signer_login=NULL",
                        250),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "commit_contributor",
                        "commit_contributor",
                        "t.user_id IN (:users)",
                        "id,commit_id,user_id,role,name,email,ordinal",
                        "id",
                        "",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "commit_file_change",
                        "commit_file_change",
                        "FALSE",
                        "id,filename,change_type,additions,deletions,changes,previous_filename,commit_id",
                        "id",
                        "",
                        0),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "project",
                        "project",
                        "t.creator_id IN (:users)",
                        "id,node_id,owner_type,owner_id,number,title,short_description,readme,template,url,closed,closed_at,is_public,creator_id,last_sync_at,item_sync_cursor,items_synced_at,field_sync_cursor,fields_synced_at,status_update_sync_cursor,status_updates_synced_at,created_at,updated_at,native_id,provider_id",
                        "id",
                        "creator_id=NULL,readme=NULL,short_description=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "project_item",
                        "project_item",
                        "t.creator_id IN (:users)",
                        "id,node_id,project_id,content_type,issue_id,content_database_id,draft_title,draft_body,archived,creator_id,created_at,updated_at,native_id,provider_id",
                        "id",
                        "creator_id=NULL,draft_title=NULL,draft_body=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "project_status_update",
                        "project_status_update",
                        "t.creator_id IN (:users)",
                        "id,node_id,project_id,body,body_html,start_date,target_date,status,creator_id,created_at,updated_at,native_id,provider_id",
                        "id",
                        "creator_id=NULL,body=NULL,body_html=NULL",
                        200),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "project_field_value",
                        "project_field_value",
                        "t.item_id IN (SELECT id FROM project_item WHERE creator_id IN (:users))",
                        "id,item_id,field_id,text_value,number_value,date_value,single_select_option_id,iteration_id,updated_at",
                        "id",
                        "",
                        150),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "connection_audit",
                        "connection_audit",
                        "t.actor_account_id = :account",
                        "id,connection_id,event_type,from_state,to_state,actor_kind,actor_ref,actor_account_id,correlation_id,detail,occurred_at",
                        "id",
                        "actor_account_id=NULL,actor_ref=NULL,detail=NULL",
                        400),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "sync_job",
                        "sync_job",
                        "t.triggered_by_user_id = :account",
                        "id,workspace_id,connection_id,kind,type,trigger_source,status,cancel_requested,started_at,finished_at,created_at,heartbeat_at,items_processed,items_total,progress,error_summary,triggered_by_user_id",
                        "id",
                        "triggered_by_user_id=NULL,progress=NULL,error_summary=NULL",
                        400),
                new JdbcPersonDataStore(
                        jdbc,
                        mapper,
                        "artifact_signal",
                        "artifact_signal",
                        "t.requested_by_user_id IN (:users) OR t.actor_user_id IN (:users)",
                        "id,workspace_id,artifact_kind,artifact_id,signal_name,revision,occurred_at,discovered_via,state,state_reason,job_id,state_changed_at,last_attempted_at,requested_by_user_id,actor_user_id",
                        "id",
                        "requested_by_user_id=NULL,actor_user_id=NULL",
                        400));
    }
}
