package de.tum.cit.aet.hephaestus.notification.push;

import de.tum.cit.aet.hephaestus.core.auth.web.CurrentAccount;
import de.tum.cit.aet.hephaestus.core.runtime.ConditionalOnServerRole;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

/**
 * The signed-in account's push devices. Only a native app session can register one, because the
 * registration is bound to that session: when it ends, the device stops receiving.
 */
@ConditionalOnServerRole
@RestController
@RequestMapping("/user/push-devices")
@Tag(name = "Push devices", description = "Push notification registration for the native app")
@PreAuthorize("isAuthenticated()")
@Validated
public class AccountPushDeviceController {

    /** Generated by the app; long enough to be unguessable, short enough to index. */
    private static final String INSTALLATION_ID = "[A-Za-z0-9-]{16,64}";

    private final PushDeviceService deviceService;

    public AccountPushDeviceController(PushDeviceService deviceService) {
        this.deviceService = deviceService;
    }

    public record PushDeviceStatusDTO(
            @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
            boolean available,

            @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
            boolean registered) {}

    public record PushDeviceRegistrationDTO(
            @NotNull @Pattern(regexp = "Expo(nent)?PushToken\\[[A-Za-z0-9_-]{8,200}\\]")
            String expoPushToken,

            @NotNull PushDevice.Platform platform) {}

    @GetMapping("/{installationId}")
    @Operation(
            summary = "Whether this server sends push notifications and this installation receives them",
            operationId = "getPushDeviceStatus")
    public PushDeviceStatusDTO status(@PathVariable @Pattern(regexp = INSTALLATION_ID) String installationId) {
        return new PushDeviceStatusDTO(
                deviceService.available(),
                deviceService.isRegistered(
                        CurrentAccount.requireId(), CurrentAccount.nativeSessionId(), installationId));
    }

    @PutMapping("/{installationId}")
    @Operation(summary = "Receive push notifications on this installation", operationId = "registerPushDevice")
    @ApiResponse(responseCode = "204", description = "Registered")
    @ApiResponse(responseCode = "400", description = "Not a native app session")
    @ApiResponse(responseCode = "409", description = "This server does not send push notifications")
    public ResponseEntity<Void> register(
            @PathVariable @Pattern(regexp = INSTALLATION_ID) String installationId,
            @Valid @RequestBody PushDeviceRegistrationDTO body) {
        UUID nativeSessionId = CurrentAccount.nativeSessionId();
        if (nativeSessionId == null) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Only the native app registers for push notifications");
        }
        if (!deviceService.available()) {
            throw new ResponseStatusException(HttpStatus.CONFLICT, "This server does not send push notifications");
        }
        deviceService.register(
                CurrentAccount.requireId(), nativeSessionId, installationId, body.expoPushToken(), body.platform());
        return ResponseEntity.noContent().build();
    }

    @DeleteMapping("/{installationId}")
    @Operation(summary = "Stop push notifications on this installation", operationId = "unregisterPushDevice")
    @ApiResponse(responseCode = "204", description = "Unregistered, or it was not registered")
    public ResponseEntity<Void> unregister(@PathVariable @Pattern(regexp = INSTALLATION_ID) String installationId) {
        deviceService.unregister(CurrentAccount.requireId(), installationId);
        return ResponseEntity.noContent().build();
    }
}
