package de.tum.cit.aet.hephaestus.notification.push;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import java.time.Instant;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.jspecify.annotations.Nullable;

/**
 * One app installation that may receive push notifications for one account, registered by the native
 * session it was signed in with. The device stops receiving the moment that session ends, whatever ended
 * it: sending checks the session, not this row.
 *
 * <p>Account-scoped, not workspace-scoped: one installation serves every workspace of its account.
 */
@Entity
@Table(
        name = "push_device",
        uniqueConstraints = {
            @UniqueConstraint(name = "uk_push_device_installation_id", columnNames = "installation_id"),
            @UniqueConstraint(name = "uk_push_device_expo_push_token", columnNames = "expo_push_token"),
        },
        indexes = @Index(name = "ix_push_device_account_id", columnList = "account_id"))
@Getter
@Setter
@NoArgsConstructor
public class PushDevice {

    @Id
    @Column(name = "id", columnDefinition = "uuid")
    private UUID id;

    @Version
    private long version;

    @Column(name = "account_id", nullable = false)
    private Long accountId;

    /** Generated by the app once per installation; the key a re-registration and an unregister use. */
    @Column(name = "installation_id", nullable = false, length = 64)
    private String installationId;

    @Column(name = "expo_push_token", nullable = false, length = 255)
    private String expoPushToken;

    @Enumerated(EnumType.STRING)
    @Column(name = "platform", nullable = false, length = 16)
    private Platform platform;

    @Column(name = "native_session_id", nullable = false, columnDefinition = "uuid")
    private UUID nativeSessionId;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private @Nullable Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private @Nullable Instant updatedAt;

    public PushDevice(
            UUID id,
            Long accountId,
            String installationId,
            String expoPushToken,
            Platform platform,
            UUID nativeSessionId) {
        this.id = id;
        this.accountId = accountId;
        this.installationId = installationId;
        this.expoPushToken = expoPushToken;
        this.platform = platform;
        this.nativeSessionId = nativeSessionId;
    }

    public enum Platform {
        IOS,
        ANDROID,
    }
}
